### ISSUE TITLE
Incorrect gain settings (crash with usrp & bladerf)

### ISSUE THREAD

**Issue by csete** [csete/gqrx#125]
When switching devices gqrx will try so set/get the gains of the previous device. In some cases this will lead to an exception such as te one discussed here:
https://groups.google.com/forum/#!msg/gqrx/h69vMymU8-c/D2OZXYYFm3EJ

USRP and Bladerf devices are known to be affected by this.

**Comment by csete** [comment]
Is this still an issue?

**Comment by andrepuschmann** [comment]
Haven't checked for a while? But I could if you like? Which version? Recent git?

**Comment by csete** [comment]
Actually, I don't think a fix was ever submitted so this is probably still an issue.
