### ISSUE TITLE
When in SSB/CW mode, setting the filter size too narrow causes DSP to freeze

### ISSUE THREAD

**Issue by AsciiWolf** [csete/gqrx#127]
DSP freezes when you use SSB or CW mode and try to set the filter size too narrow - 0.3k or less. (To do that, you must zoom in first.)

**Comment by AsciiWolf** [comment]
The issue seems to be fixed.

**Comment by csete** [comment]
Cool, I don't remember if we fixed anything, could be that the gnuradio block is behaving differently now.
