### ISSUE TITLE
Add support for generic audio input

### ISSUE THREAD

**Issue by csete** [csete/gqrx#13]
Implement support for using standard soundcards as input I/Q source.

**Comment by csete** [comment]
This is now theoretically possible through the SoapySDR driver. Someone needs to test it and report back.

**Comment by csete** [comment]
Nobody to test it.

**Comment by tdbone1** [comment]
SoapySDRUtil --find not finding my laptops built-in sound card therefore i think gqrx isnt working with it.
en1gma@M4800:~$ lsb_release
LSB Version:	core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
en1gma@M4800:~$ uname -a
Linux M4800 4.18.0-19-generic #20~18.04.1-Ubuntu SMP Fri Apr 26 09:04:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
en1gma@M4800:~$ SoapySDRUtil --info
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

Lib Version: v0.7.1-myriadrf1~ubuntu18.04
API Version: v0.7.1
ABI Version: v0.7
Install root: /usr
Search path:  /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7
Search path:  /usr/local/lib/x86_64-linux-gnu/SoapySDR/modules0.7               (missing)
Search path:  /usr/local/lib/SoapySDR/modules0.7                                (missing)
Module found: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/libHackRFSupport.so (0.3.3)
Module found: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/libLMS7Support.so   (19.01.0)
Module found: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/libairspySupport.so (0.1.2)
Module found: /usr/lib/x86_64-linux-gnu/SoapySDR/modules0.7/librtlsdrSupport.so (0.3.0)
Available factories... airspy, hackrf, lime, rtlsdr
Available converters...
 -  CF32 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS16 -> [CF32, CS16, CS8, CU16, CU8]
 -  CS32 -> [CS32]
 -   CS8 -> [CF32, CS16, CS8, CU16, CU8]
 -  CU16 -> [CF32, CS16, CS8]
 -   CU8 -> [CF32, CS16, CS8]
 -   F32 -> [F32, S16, S8, U16, U8]
 -   S16 -> [F32, S16, S8, U16, U8]
 -   S32 -> [S32]
 -    S8 -> [F32, S16, S8, U16, U8]
 -   U16 -> [F32, S16, S8]
 -    U8 -> [F32, S16, S8]
en1gma@M4800:~$ SoapySDRUtil --find
######################################################
##     Soapy SDR -- the SDR abstraction library     ##
######################################################

No devices found!
en1gma@M4800:~$ gqrx --help
linux; GNU C++ version 7.3.0; Boost_106501; UHD_003.010.003.000-0-unknown

Controlport disabled
Gqrx software defined radio receiver 2.11.5
Command line options:
  -h [ --help ]         This help message
  -s [ --style ] arg    Use the give style (fusion, windows)
  -l [ --list ]         List existing configurations
  -c [ --conf ] arg     Start with this config file
  -e [ --edit ]         Edit the config file before using it
  -r [ --reset ]        Reset configuration file

en1gma@M4800:~$
