### ISSUE TITLE
bad_alloc Problem on Debian

### ISSUE THREAD

**Issue by ozanguven** [csete/gqrx#184]
Hello,

I am trying to run Gqrx on Debian Wheezy, however I get below error:

# gqrx
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
AborMy system:

My system:
# uname -a
Linux debian 3.2.0-4-amd64 #1 SMP Debian 3.2.60-1+deb7u1 x86_64 GNU/Linux

I have DVB-T dongle based on the RTL2832U chipset and debian recognize it without any issue.

Gqrx version: 2.2.0.137.eca0ea7-1~bpo70+1

Do you have any idea or suggestion for running gqrx?

Thanks.

**Comment by csete** [comment]
Try the latest version. Version 2.2 is very old.
