### ISSUE TITLE
Renamed I/Q recording causes segfault

### ISSUE THREAD

**Issue by courtarro** [csete/gqrx#199]
I created an I/Q recording. I then renamed the recording to make it easier for me to remember what I was doing with it. Afterward, gqrx started crashing in two distinct places when that renamed .raw file existed in the recordings directory:
1. Whenever I clicked the renamed file, in order to play it, I got an immediate segfault.
2. Ignoring the renamed file ... whenever I clicked "record" to start a new file, immediate segfault (as long as the renamed file was present).

I'm guessing that gqrx needs to use the filename to know what center frequency and bandwidth to show onscreen, and it doesn't gracefully handle the name not matching its pattern?

**Comment by andimik** [comment]
So, what is the naming convention for such a file? I'd like to use a prerecorded rtl_sdr file (2048 kHz).

**Comment by argilo** [comment]
It appears this was fixed in #366.
