### ISSUE TITLE
Bandwidth not properly saved in bookmarks

### ISSUE THREAD

**Issue by pferreir** [csete/gqrx#216]
Whenever I save a bookmark the bandwidth defaults to 2800 and not to whatever I currently have.
Is this supposed to happen?

**Comment by charlylima** [comment]
I can not reproduce it. 
For example: I set Frequency to 140 MHz, Mode "Narrow FM", Filter "User 42k", then create a Bookmark "Test1" and I have got the right Bandwidth 42000 in the Bookmarks Table.

Please tell us exactly how to reproduce the error.

**Comment by pferreir** [comment]
I'll have a look at home. Sorry, haven't had the time yet!

**Comment by csete** [comment]
It works for me too.
