### ISSUE TITLE
Remote control enhancements (Filter bandwidth, start demod)

### ISSUE THREAD

**Issue by khaytsus** [csete/gqrx#218]
There are two things I think which are missing from the GQRX remote control interface.  The ability to get/set the filter bandwidth and the ability to start/stop demodulation.  Adding these would enhance utilities that use the remote interface, such as my scanning script.  Thank you!

**Comment by csete** [comment]
What do you mean with start/stop demodulation?

**Comment by khaytsus** [comment]
Add a command to start or stop modulation in the remote control interface, combined with the remote enabled it is less buttons to push to control gqrx remotely.

**Comment by csete** [comment]
Do you mean the same function as the start/stop DSP button? It's the word modulation that confuses me since the demodulator is just a single block in a long processing chain and it can not be started/stopped on its own.

**Comment by khaytsus** [comment]
Ah sorry, yes, that's what I mean.  I think I have an Android app which refers to it as start/stop demod, but yes I am meaning the start/stop DSP in GQRX.  :)
