### ISSUE TITLE
Store/Restore Remote Control enabled setting

### ISSUE THREAD

**Issue by khaytsus** [csete/gqrx#219]
Currently GQRX does not store/restore the remote control enabled setting.  It would be really nice if that would be set on startup.  Thank you!

**Comment by csete** [comment]
Would it really be wise to enable the network interface automatically in a GUI application?

**Comment by khaytsus** [comment]
Default is localhost, if the user changes that then they know what they are doing. Also, not automatic, just enable if enabled at last exit.
