### ISSUE TITLE
Frequency going in the wrong direction

### ISSUE THREAD

**Issue by joushx** [csete/gqrx#224]
When changing the frequency with the freqCtr component, the frequency moves into the wrong direction when using digits after the dot.

The initial state:

![bildschirmfoto vom 2015-02-01 18 45 11](https://cloud.githubusercontent.com/assets/832178/5993038/98106e20-aa42-11e4-8e2f-f5389b91b5b7.png)

Going up by 0.1 MHz:

![bildschirmfoto vom 2015-02-01 18 45 27](https://cloud.githubusercontent.com/assets/832178/5993039/99c5659a-aa42-11e4-997f-b52953de3446.png)

It goes down when it should go up and vice versa.

**Comment by csete** [comment]
Ehm, you say "going up by 0.1 MHz" and what I see on the screenshot is that it changes from 95.6 to 95.7 MHz. I'm not sure I understand what you think is wrong here? Perhaps you can elaborate.

**Comment by joushx** [comment]
If I increase the frequency the FFT diagram is moving to the right so I can see frequencies to the left of the previous view. Notice the "peak" at the right: I want to go to a higher frequency, but it moves to the right. It was at ~94.65 MHz and is now at ~94.7 MHz. If it would have moved to the left it still would be at ~94.65 MHz.

**Comment by csete** [comment]
Sounds like you have the I and Q channels reversed for some reason but it's hard to tell why without knowing anything about your setup.

**Comment by csete** [comment]
By the way, try to reproduce this with a real signal, not spurs. Spurs can occur at baseband and then move randomly regardless of whether you tune up or down.

**Comment by joushx** [comment]
Oh, I accidentaly checked the "Swap I/Q" checkbox. This resolves the issue. Thank you for your time and your great project!

The said peak was a real radio station by the way.
