### ISSUE TITLE
RDS "Radio Text" cuts off

### ISSUE THREAD

**Issue by paulguy** [csete/gqrx#229]
On commit 1ff469782eaab959cc729137622a3818e94eca73 the "Radio Text" field in the RDS panel cuts off at least a character.  If you need more information i should be able to provide.  I'm using Gentoo Linux on MATE desktop 1.8.0.

![gqrx_rds_cutoff](https://cloud.githubusercontent.com/assets/965996/6766312/996bc5f2-cfd7-11e4-8236-ec697368ec0b.png)

**Comment by csete** [comment]
Thanks. Maybe @stanojr will have some time to look into it.
