### ISSUE TITLE
Modifying bookmark tags and hitting Cancel removes all tags from bookmark

### ISSUE THREAD

**Issue by khaytsus** [csete/gqrx#234]
If you go to modify a bookmark Tags, but hit Cancel, it currently removes all tags from the bookmark.

Using GQRX as of revision f3bb0ab080197b0738dc5713c8222c168f2e1850

**Comment by csete** [comment]
Hi @khaytsus  
Could you confirm that the issue is fixed now?

**Comment by khaytsus** [comment]
I must be missing something, I have no way to modify an existing Bookmark now?  If I right-click an existing bookmark, I get the options to Delete Bookmark or Add Bookmark.

**Comment by khaytsus** [comment]
Okay, I figured out double-clicking the Tag will let me modify the tag.  Others you edit inline.  Working fine now, although a dialog for modifying the whole Bookmark would be nice vs inline.

**Comment by khaytsus** [comment]
Tested on 8ffff0c for reference
