### ISSUE TITLE
Bookmark labels in FFT draw over each other in dense channel bookmarks

### ISSUE THREAD

**Issue by khaytsus** [csete/gqrx#236]
When there are many bookmarks in one spot in the spectrum, GQRX puts the labels over-top of each other in the FFT area.  It appears to currently only offset by 3 or so vertical levels, so if you have many bookmarks in one place the labels are drawn over top of each other.

It does not appear to matter how large the FFT vs Waterfall is, although I could see that there would be a limitation that the labels would not draw outside of the FFT area.

Screenshot here:  https://dl.dropboxusercontent.com/u/334233/gqrx-bookmark-labels.png

Using GQRX as of revision f3bb0ab080197b0738dc5713c8222c168f2e1850

**Comment by kolbma** [comment]
Can you please explain again or provide an accessible image?!

**Comment by kolbma** [comment]
![gqrx-bookmarks-dense](https://user-images.githubusercontent.com/5228369/76540282-3838e400-6482-11ea-9eda-e471bdc1862b.png)
Looks ok I think?!

**Comment by khaytsus** [comment]
Well, it is almost 5 years old, I guess I cleaned out my Dropbox ;)  I too do not really recall what this originally looked like, but if you have FRS in your bookmarks, go where those are and zoom out.  This may have been worse 5 years ago, not sure.  https://i.imgur.com/0lALWi4.png

This is FRS/GMRS plus some commercial repeaters etc, standard bookmarks I have, nothing contrived here.  Zoomed out it does look kind of bad, but zoomed in a bit it's okay.  Again, I don't recall the original so it might have been worse.  I don't think as it is this is a big deal.
