### ISSUE TITLE
negative ppm problem

### ISSUE THREAD

**Issue by redbobcat** [csete/gqrx#246]
Can't set ppm below zero, down button is grey. From keyboard only -0,0.
v2.3.2-107-g04de8
![screenshot from 2015-06-15 22 21 28](https://cloud.githubusercontent.com/assets/12900525/8168653/efb9fbae-13ac-11e5-8515-c936723499c7.png)

**Comment by csete** [comment]
It should be fixed now.

**Comment by redbobcat** [comment]
Thanks, it works now.
