### ISSUE TITLE
Frequency correction settings per-device

### ISSUE THREAD

**Issue by troffasky** [csete/gqrx#252]
None of the devices I own require the same frequency correction PPM, but this is a global setting. I don't know how many device types will report their serial number [which would be the best approach] but at least having an option per device type would be useful.

**Comment by csete** [comment]
Gqrx supports using different configuration files and the idea was indeed to allow using different configuration files for different devices. A specific configuration file can be loaded on the command line (see "gqrx -h" for options) or from the GUI.

**Comment by csete** [comment]
No response for a long time.
