### ISSUE TITLE
GQRX wont compile on Ubuntu 14.04 (LinuxMint) when boost requires -mt flag on pybombs

### ISSUE THREAD

**Issue by JannF** [csete/gqrx#254]
As the title says, GQRX won't compile on Linux Mint (Ubuntu based) because it's recipe needs the boost library with -mt flag.
Removing -mt flag from the recipe lets me at least compile.

**Comment by csete** [comment]
Thanks, but since the recipe is in pybombs and not in gqrx you should report it there.

**Comment by ckuethe** [comment]
I'm working on fixing that recipe... it's been annoying me for a year.

Those bums at Boost still haven't addressed the issue that's been open for over 8 years: https://svn.boost.org/trac/boost/ticket/1094

**Comment by ckuethe** [comment]
https://github.com/gnuradio/pybombs/issues/171

**Comment by mat650** [comment]
with a fresh pybombs fetch
With mkdir build
cd build
qmake ../
the problem is fixed but Segfault when i 'm trying to start gqrx

**Comment by ckuethe** [comment]
Fixed by gnuradio/recipes#38
