### ISSUE TITLE
Won't build when Marcus Leech Build Script Used Aug 1, 2015 and fresh install Ubuntu 14.04 Trusty used

### ISSUE THREAD

**Issue by Urnip** [csete/gqrx#257]
Hi,

I literally got GQRX to build last night with a fresh version of ubuntu 14.04 Trusty, fresh version of Marcus Leech's build script on sbrac.org.  Same circumstances at 1:59 am UTC no go.  Any info or a fix you could give to compile gqrx from source files would be great.  I'm trying to learn about software and the best way I can figure to do it is to make a minor change to GQRX and compile it.

Thanks,

**Comment by csete** [comment]
Nothing has changed in gqrx between "last night" and 1:59 am UTC.

I can't help you with random scripts downloaded from the Internet.
