### ISSUE TITLE
Feature request: spur list and highlighting

### ISSUE THREAD

**Issue by darrenfreeman** [csete/gqrx#277]
My SDR has a lot of spurs, and I have been slowly adding them to the bookmarks file as "Spur", tagged as "Spurs". Of course I keep this tag unchecked, but it's handy for ruling out a CW signal as being real. I just unplug the antenna and go looking.

For now, what would be nice is to move this into a separate file from the main bookmarks file. Everything in there would load as a bookmark called Spur, tagged as Spurs, demod off, etc. The colour would be set to red, or some user defined colour.

They would be treated differently from regular bookmarks in the following way. If you apply a ppm frequency correction, then the spur frequencies would shift with that correction so as to maintain them at the same hardware frequency. In the file, they would be stored as hardware raw frequencies. (You'd expect many of them to line up with the nominal clock frequency and be easy to guess.)

In the distant future, what would then be awesome is to automate the process of scanning every say 1 MHz, and automatically detecting any spurs found over a long observation period (say averaging 1000x 32768-point FFTs), and adding them to the file.

So you could take a brand new receiver, initialise the spurs list, and go.

And you'd someday want to have one spurs file per hardware device, and automatically change files as you change device.

Someday! For now, I'd like to do this manually with a text editor, and have the UI capable of displaying them differently from bookmarks, and without cluttering the bookmarks file.

**Comment by csete** [comment]
Outside the scope of gqrx.
