### ISSUE TITLE
Application fails to exit after closing

### ISSUE THREAD

**Issue by darrenfreeman** [csete/gqrx#278]
This has happened to me twice, and I'm not sure what you can do about it since I know this is rather vague.. But I thought I'd put it out there in case it helps.

Sometimes gqrx stays running after all the windows are closed. It can block a fresh instance from talking to the hardware, and I've had it cause audio quality issues with pulseaudio.

(I think that has to be pulseaudio's fault.. but the mixer showed a slider for gqrx, and dragging that up and down caused static to be heard through the speakers.)

**Comment by csete** [comment]
Can not reproduce this on any platform that I use.
