### ISSUE TITLE
Bookmarks drawn at wrong frequencies when near the limit frequency

### ISSUE THREAD

**Issue by darrenfreeman** [csete/gqrx#279]
I have bookmarks that I manually entered, at higher frequencies than the highest my device will do (1766 MHz for a RTL-SDR).

If I set my receiver frequency to this limit, then slowly tune down in frequency, the spectral features move to the right of the FFT as you'd expect. But the bookmarks move faster! So I have bookmarks that actually cross over the features that I'd intended to label.

I think there must be an issue where the scale factor is calculated incorrectly due to clipping against the limit frequency. We must remember that the right side of the FFT is allowed to be greater than the maximum selectable centre frequency.

Or at least this is what I think is going on. I can go to 900 MHz and scroll around, and the bookmarks that tag the spurs move along accurately tracking them. But at 1765 MHz, the bookmark moves hundreds of kHz either side of the spurs.

**Comment by argilo** [comment]
I'm unable to reproduce this. Are you sure the spurs you were looking at were not third-order intermodulation products?
