### ISSUE TITLE
Bookmark labels sometimes missing the leftmost pixel of text

### ISSUE THREAD

**Issue by darrenfreeman** [csete/gqrx#281]
This may depend on font and other system settings.

I have occasionally noticed that the first pixel or so worth of the bookmark label is not drawn on the FFT display. So for example I've had ISS display as SS, I've had MIX display like VIIX. (And by that I mean MIX but with the left vertical line of the M missing.)

Please keep an eye out for this and see if you can confirm on your particular settings.

I can say for certain that this is happening on my system, but it's not happening on every bookmark. Some Ms are cut off, some are correct. I'm guessing Qt is rendering fonts internally with fractional pixel offsets for antialiasing, and only occasionally the whole thing ends up shifted left by one pixel.

**Comment by argilo** [comment]
I have been unable to reproduce this problem. It's possible that #828 could have fixed it, since it changed the width calculation to use `boundingRect`. If you're still able to reproduce on the latest Gqrx, let me know.
