### ISSUE TITLE
Warning after make, not run gqrx

### ISSUE THREAD

**Issue by sabas1080** [csete/gqrx#283]
A have a problem, after of make show this

warning: libvolk.so.1.0.2, needed by /usr/local/lib/libgnuradio-analog.so, may conflict with libvolk.so.0.0.0

and not run gqrx

~/gqrx/build$ ./gqrx
linux; GNU C++ version 4.9.2; Boost_105500; UHD_003.010.git-29-gbc80e972

gr-osmosdr v0.1.4-48-g86ad5842 (0.1.5git) gnuradio 3.7.8
built-in source types: file fcd rtl rtl_tcp uhd bladerf rfspace 
Using Volk machine: sse4_2_64_orc

Thanks

**Comment by csete** [comment]
As the message says, you have two versions of libvolk installed and they conflict with each other. You have probably installed gnuradio from source while you have already had it installed via the package manager. Uninstall the one that you don't need.

Closing as this is not a gqrx issue.

**Comment by sabas1080** [comment]
Thanks
