### ISSUE TITLE
raw IQ file info

### ISSUE THREAD

**Issue by cyber5tar86** [csete/gqrx#301]
Hi!
I've a question about IQ raw data saving... can you give me some infos about it (metadata, bit per sample, etc...) ?

**Comment by csete** [comment]
There is no meta data. Just raw samples in float complex format, i.e. 32 bit floats interleaved IQIQIQ... samples. It's the same format you get with a gnuradio file sink.

We use this issue tracker for bugs and feature requests. For user support please use our mailing list:
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/gqrx
