### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by csete** [csete/gqrx#31]
This is general issue that concerns exceptions.

Many GNU Radio blocks throw an exception in their constructor if something goes wrong. Currently, gqrx doesn't catch any of these so the application will just crash. We should catch the exception and have a safe fallback or bail out with error messages that users can understand.

**Comment by csete** [comment]
The latest commit adds error handling when device errors occur during start up.

**Comment by ZeroChaos-** [comment]
It's been a little while since you have had a tagged release, are you planning one soon?  This feature alone is worth a point release, as is gr-rds support.

**Comment by csete** [comment]
I'll try to make one in the next few weeks. I'd like to have a few OS X fixes included.
