### ISSUE TITLE
Mode doesn't switch to "WFM (oirt)" from bookmark.

### ISSUE THREAD

**Issue by kukabu** [csete/gqrx#313]
Hello

When I choose bookmark with "WFM (oirt)" mode doesn't switch to.

**Comment by csete** [comment]
There was a short period where the mode names were different and your bookmark was created with that mode name, which now no longer exists. So just update your bookmark or recreate it and it should work again.

**Comment by kukabu** [comment]
No, names match. It creates after e2497fde038d7c8d05c77e6685e1464e86f03653.
```
$ fgrep oirt .config/gqrx/bookmarks.csv
   549750000; ТВК30 РОССИЯ 1 САМАРА    ; WFM (oirt)          ;     200000; TV
```

**Comment by csete** [comment]
Actually, it looks like the correct mode is selected, but the mode shown in the mode selector is not updated. Is that also what you observe?

**Comment by csete** [comment]
I believe this is fixed now, but feel free to reopen if there are still issues.

**Comment by kukabu** [comment]
Thanks! Fixed.
