### ISSUE TITLE
Menu not visible in classic gnome

### ISSUE THREAD

**Issue by ntoulasd** [csete/gqrx#321]
I use ubuntu 14.04 (Greek) with flashback environment.
Menus are not visible !
![2016-01-03 13 04 59](https://cloud.githubusercontent.com/assets/1451169/12078435/d0d60658-b21a-11e5-8286-359c35cf39dc.png)

**Comment by csete** [comment]
Sorry to hear that, but it sounds like desktop issue or an integration of Qt into the desktop, no?

I use standard Qt toolkit without anything special that should cause something like this. So I have no idea  what I can do about it.

**Comment by ntoulasd** [comment]
Thanks
sudo apt-get remove --purge appmenu-*
fix my problem

Good work, keep going.

**Comment by csete** [comment]
Thanks a lot for the info, Dimitrios!
