### ISSUE TITLE
Channel Filter Offset values 0 > x > -1 do not display negative sign

### ISSUE THREAD

**Issue by tomswartz07** [csete/gqrx#323]
Hi there!

I think I've found a small bug with the way that the Channel Filter Offset is displayed.

When the value is between 0 and -1 (e.g. -0.3kHz) there is no negative sign before the leading zero.
Here's a [screenshot](http://oi68.tinypic.com/i6a78h.jpg) where this is evident.

Cheers,

**Comment by csete** [comment]
Thanks, I'm aware of the issue and I thought there was already a bug open, but perhaps I remember wrong.

**Comment by tomswartz07** [comment]
Oops, looks like there was: https://github.com/csete/gqrx/issues/247

Apologies for my oversight. I'll close this and subscribe to that issue.

**Comment by csete** [comment]
No problem. I couldn't remember it either.
