### ISSUE TITLE
Main window height

### ISSUE THREAD

**Issue by rag2** [csete/gqrx#327]
# Main window height is too much for **768** height screen
A 768 height screen is found on many laptops or cheap screens.
As of GQRX 2.5, the minimum height of the standard screen layout seems to be **787** pixels.

## Workaround
One of the control panels may be minimised, thus losing the associated display and control, and the main screen resized. However, when the panel is restored, such that 2 panels are shown, the main screen returns to 787 pixel height.

## Request
That the QGRX GUI be set such that all the functionality fits inside a 768 pixel height screen.

**Comment by csete** [comment]
Thanks Robin. I think this happened with increasing the button sizes due to some constraints on OS X. I will try to fix it for the next release.

**Comment by csete** [comment]
I managed to squeeze the layouts and add some scroll windows so that the window can now almost fit into 800 x 600 pixels, though still depending on the desktop theme.

![screenshot_302](https://cloud.githubusercontent.com/assets/306178/12434839/9bd0dd2e-bf09-11e5-82ab-231a8bf5eeca.png)

**Comment by rag2** [comment]
Alex, many thanks for that!

**Comment by csete** [comment]
I had to re-increase the height a bit, otherwise it would be broken on OS X, but still below 700 pixels. I'll make a new release soon.
