### ISSUE TITLE
gqrx not opening on osx

### ISSUE THREAD

**Issue by Brett99** [csete/gqrx#331]
When I try to open the application, it says "gqrx quit unexpectedly" every time.

**Comment by Brett99** [comment]
[Here is the crash log](https://github.com/csete/gqrx/files/104271/crash.txt)

**Comment by Brett99** [comment]
My fault, I was missing the line '127.0.0.1 localhost' in my host file.

**Comment by nate-nate** [comment]
I'm having the same issue. 
Could you explain how you added the localhost line to your host file please?

**Comment by Brett99** [comment]
Edit the file at /etc/hosts

Add the following line to this file: '127.0.0.1 localhost'

**Comment by nate-nate** [comment]
My terminal isn't prompting me for my admin password (i'm the only user/admin)
instead it says I'm not permitted to access my hosts file

Thanks for the help

**Comment by nate-nate** [comment]
sudo nano worked - looks like I have that line in the file already!
