### ISSUE TITLE
Reception begins if RDS flag is set to enable on RDS Tab

### ISSUE THREAD

**Issue by gerbert** [csete/gqrx#334]
If application is started and the reception is off, clicking on RDS Status checkbox to enable the RDS causes the reception to begin. In this case the waterflow and spectrum doesn't show anything. Yet the reception is active.
Affects v.2.5.2

**Comment by csete** [comment]
Indeed, there are a few strange things in this area.

**Comment by argilo** [comment]
Fixed in 677d83324e0d620648c24f1ac30e3fd8b1999b9f.
