### ISSUE TITLE
Lsb filter resize error

### ISSUE THREAD

**Issue by ntoulasd** [csete/gqrx#340]
While drag to resize filter in lsb mode. Width becomes immediately 0.1
Usb mode works fine.
![2016-02-03 20 15 14](https://cloud.githubusercontent.com/assets/1451169/12792209/647ce588-cab3-11e5-95b5-adf8616ed424.png)

**Comment by csete** [comment]
I think this is fixed in git. Please always include info about which version you are using.

**Comment by ntoulasd** [comment]
I am sorry, I use 2.5.2 version from ppa.

**Comment by csete** [comment]
Ok, no problem. So, this is fixed and will be available in 2.5.3 due in a few days.
