### ISSUE TITLE
Feature request: Support for LNB LO freq for the Ku band

### ISSUE THREAD

**Issue by ewpereira** [csete/gqrx#343]
It would be nice to be able to set the LNB LO frequency to at least 10 GHz in order to use LNBs for the Ku band. This will be specially useful for the upcoming Es'Hail 2 linear transponder in 10 GHz.

73, Edson PY2SDR

**Comment by csete** [comment]
Will take a look at it.

**Comment by csete** [comment]
It is now possible to set the frequency up to 999 GHz, and the LNB LO between +/- 500 GHz -- I need to set some limits :-)
