### ISSUE TITLE
Error building from source on armhf

### ISSUE THREAD

**Issue by backbonemedia** [csete/gqrx#345]
I am trying to build gqrx from source using qmake on the Cubieboard 1. I Tried master and 2.5.3. The following error occured:

`g++ -c -pipe -O2 -Wall -W -D_REENTRANT -fPIE -DQT_NO_DEBUG -DQT_NO_DEBUG_OUTPUT -DVERSION="\"2.5.3\"" -DWITH_PULSEAUDIO -D_REENTRANT -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_NETWORK_LIB -DQT_GUI_LIB -DQT_CORE_LIB -I/usr/lib/arm-linux-gnueabihf/qt5/mkspecs/linux-g++ -I../../gqrx-2.5.3 -I../src -isystem /usr/local/include -isystem /usr/include/arm-linux-gnueabihf/qt5 -isystem /usr/include/arm-linux-gnueabihf/qt5/QtWidgets -isystem /usr/include/arm-linux-gnueabihf/qt5/QtNetwork -isystem /usr/include/arm-linux-gnueabihf/qt5/QtGui -isystem /usr/include/arm-linux-gnueabihf/qt5/QtCore -I. -I. -I. -o parser_impl.o ../src/dsp/rds/parser_impl.cc
{standard input}: Assembler messages:
{standard input}:10527: Warning: end of file not at end of a line; newline inserted
{standard input}:11457: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11461: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11471: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11474: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11487: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11489: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11500: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11502: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11504: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11513: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11581: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11606: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11623: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11630: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11636: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11652: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
{standard input}:11655: Error: cannot represent T32_OFFSET_IMM relocation in this object file format
g++: internal compiler error: Getötet (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <file:///usr/share/doc/gcc-4.6/README.Bugs> for instructions.
make: *** [parser_impl.o] Fehler 4`

What is that message about? Successfully built and installed gnuradio.

**Comment by csete** [comment]
Well, the error message says "internal compiler error". I have noticed compiler warnings while building gr-rds, but it always got through. You could try a newer version of gcc.

Having said that, you should be aware that it is extremely unlikely that you will get anything useful out of running gqrx on a single core ARM processor.
