### ISSUE TITLE
Bandwitdth doesn't switch to user defined from bookmark.

### ISSUE THREAD

**Issue by kukabu** [csete/gqrx#349]
Hello
When I trying switch to
```
   158375000; 158375000            ; Narrow FM           ;      30000; Untagged
```
gqrx doesn't apply 30000 on waterfall

**Comment by csete** [comment]
Is it only the display, i.e. is the filter itself set correctly?

**Comment by kukabu** [comment]
It seems that only the display, bit I don't know how to properly check
