### ISSUE TITLE
Feature Request: Audio Waterfall

### ISSUE THREAD

**Issue by devnulling** [csete/gqrx#355]
I think it would be a nice feature to have an audio waterfall to visualize the audio FFT over time. It would be useful when looking at HF signals like CW/MFSK/FSK/etc similar to using baudline on the audio output - http://i.imgur.com/Wwg6gnu.png

**Comment by csete** [comment]
The audio plotter is the same widget as used for the main FFT, so basically only the controls to switch between FFT and waterfall are missing.

**Comment by csete** [comment]
I have now enabled the waterfall in the audio FFT. The split percentage can be adjusted under options. Other settings can be made configurable if necessary, just open a new issue.
