### ISSUE TITLE
libgnuradio-osmosdr not found

### ISSUE THREAD

**Issue by sprakashb** [csete/gqrx#356]
Using Ubuntu 15.10
Did exactly as directed on GQRX installation page
The following error shown when running gqrx
"gqrx: error while loading shared libraries: libgnuradio-osmosdr.so.0.1.4: cannot open shared object file: No such file or directory"

libgnuradio-osmosdr0.1.4 is installed (as seen in synaptic)
In synaptic the properties show " /usr/lib/x86_64-linux-gnu/libgnuradio-osmosdr.so.0.1.5git"    installed

Help!

TIA

**Comment by csete** [comment]
Perhaps you have some source installations left? Anyway,I recommend you try the mailing list as instructed on http://gqrx.dk/user-support . We only use this for bug and feature request tracking.
