### ISSUE TITLE
Cannot get UDP stream working on Mac OS X (El Capitan)

### ISSUE THREAD

**Issue by huston007** [csete/gqrx#365]
Hello. I really love Gqrx software, it's the best SDR UI for Mac OS at the moment.
Now I use latest available version *2.5.3*.

But I want go further. I need UDP output to connect external decoders like https://github.com/szechyjs/dsd

So, to achieve this I need to get UDP sound stream from Gqrx. When I press "UDP" button in UI, it presses and seems to be OK, but I can't get any UDP stream from it. `nc -l 7355 -u` shows nothing as well as `socat UDP-RECV:7355 -`.

So, please, help me to make it work. I tried another Mac, Gqrx 2.4 with and have the same issue.

**Comment by csete** [comment]
Hi,
Have you checked issue #363 opened just a few days ago? It sounds like the same problem

**Comment by huston007** [comment]
@csete Thanks for you point.
I've just used command `nc -u -l localhost 7355 ` from this issue and got the UDP stream at last : )
So it seems to be network issue or something like that. But it doesn't work without host parameter. 

Thank you again for quick answer. My issue is closed.

**Comment by csete** [comment]
Ok, well, if you don't see any data at the other end then it could be some setting in OS X. I have no idea about that, sorry. I recall other people talk about such issues some time ago, maybe it was on the mailing list, so please try to ask there.

**Comment by csete** [comment]
Ok, thanks for the update, and never mind my last comment.

**Comment by alexf91** [comment]
I have the same problem.
Changing the UDP Host to 127.0.0.1 instead of localhost fixes this problem for me. In my case, this is caused by IPv6 (at least I think it is) and not by gqrx.

**Comment by csete** [comment]
@alexf91 @huston007 Thanks for the info. I have added it to the web page about this topic at http://gqrx.dk/doc/streaming-audio-over-udp
