### ISSUE TITLE
src/qtgui/plotter.cpp: 3 * bad size in memset ?

### ISSUE THREAD

**Issue by dcb314** [csete/gqrx#372]
1.

src/qtgui/plotter.cpp:210:40: warning: 'memset' used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]

Source code is

   memset(m_wfbuf, 255, MAX_SCREENSIZE);

but

../BUILD/gqrx-sdr-2.5.3/src/qtgui/plotter.h:    qint32      m_wfbuf[MAX_SCREENSIZE];

Suggest new code

   memset(m_wfbuf, 255, MAX_SCREENSIZE * sizeof( m_wfbuf[0]));

2.

src/qtgui/plotter.cpp:547:40: warning: 'memset' used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]

3.

src/qtgui/plotter.cpp:875:44: warning: 'memset' used with length equal to number of elements without multiplication by element size [-Wmemset-elt-size]

Duplicates

**Comment by csete** [comment]
We need to find out what the original intention was. I think the array should/could be bytes instead.
