### ISSUE TITLE
remote control: reset offset to 0 when hardware freq needs to be changed 

### ISSUE THREAD

**Issue by cavedon** [csete/gqrx#374]
When using the remote control and setting a new frequency, if the new frequency is close enough gqrx will change the offset and not the hardware frequency. That's good.

However if the hardware frequency needs to be changed, gqrx will change the hw frequency and preserve the offset.
This means that if you are e.g. scanning a set of frequency (e.g. with gqrx-scan) you may end up with an offset pushed higher and higher, and you end up scanning all the channels by changing the hw freq every time and having an offset close the maximum allowed.

I hope my explanation is clear enough. I see two ways of addressing this:
1. the remote plugin resets the offset when it cannot set the new frequency changing just the offset
2. the main window  resets the offset when it cannot set the new frequency changing just the offset

I am about to attach a pull request for 1.

**Comment by csete** [comment]
I think solution 1 is fine and thanks for the patch.
