### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by Xeddius** [csete/gqrx#382]
Gqrx latest repo, a month ago, no issues.
Today I have tried to find a solution to no avail.
Problem: No matter what I try, running gqrx results in my terminal spitting
Segmentation Fault
and nothing else. No error codes, no extra text.
gdb gqrx produces NOTHING of value.
I'm at a loss. I can't figure out what is causing it, but I'm hopeful someone knows why this is happening.
Linux Mint 17.3 32-bit (Ubuntu 14.04)

**Comment by csete** [comment]
Let's keep the conversation at one place
https://groups.google.com/d/msg/gqrx/b1HCq-W2e4g/UtIvfhgxPwAJ
