### ISSUE TITLE
Release device when DSP processing is off

### ISSUE THREAD

**Issue by yuvadm** [csete/gqrx#384]
As gqrx is currently implemented, an RTLSDR device is acquired upon launch and only released when the gqrx process terminates. This means that any attempt to acquire the device during this time in any other process will fail. This is not very elegant behavior.

Is there any limitation why not to release the device when there's no DSP processing taking place?

A possible use case here can be to use gqrx to fine tune for a frequency, and then turn off DSP processing so that processing can be done in another, perhaps more specific, program.

**Comment by csete** [comment]
Gqrx is just a GUI and doesn't have any direct access to the devices. You probably want to take a look at the start/stop functions in gr-osmosdr.

**Comment by alexf91** [comment]
At least for the BladeRF, the start/stop functions don't release the device.
It only gets released when the Top-Block is destroyed.

**Comment by yuvadm** [comment]
@csete is it possible to use gr-osmosdr in any other way that resolves this issue?

**Comment by alexf91** [comment]
The start and stop functions are not exposed by the public interface of gr-osmosdr.
I don't think there is a way other than destroying the source when DSP is disabled and creating a new one when it is enabled again.

**Comment by yuvadm** [comment]
@alexf91 is there any significant performance penalty (or otherwise) in doing that?

**Comment by csete** [comment]
That's what happens when you open the I/O configurator and press the OK button. It destroys the device and creates a new one. The problem with that - aside from the performance penalty - is that one is not supposed to do that with GNU Radio objects. Basically, we a re just lucky that it works.

As I said, the right place to add device open / close is in the start / stop functions of the backend.

**Comment by alexf91** [comment]
Performance is probably not an issue here, but the correct way to achieve the use case you mentioned would be the implementation of raw-IQ streaming.

**Comment by yuvadm** [comment]
@csete's comment makes sense to me. If no other workaround exists in this case, I'll take this upstream to gr-osmosdr.

**Comment by csete** [comment]
Ok, I'm closing this issue since there is nothing do in gqrx.
