### ISSUE TITLE
Small negative frequency offsets are displayed incorrectly

### ISSUE THREAD

**Issue by Cat-Ion** [csete/gqrx#388]
If the frequency offset is negative and less than 1 kHz, e.g. -0.99 kHz, the widget in the receiver options shows it as 0.990 kHz instead.

**Comment by csete** [comment]
Hmm, I thought there was already an issue about this because it has been a known issue since the beginning, but I can not find it. Perhaps we only discussed it on the mailing list. Anyway, I am hoping someone will send a patch fixing this.

**Comment by csete** [comment]
Fixed with commit #86439028
