### ISSUE TITLE
Cannot play i/q anymore

### ISSUE THREAD

**Issue by michelinok** [csete/gqrx#403]
Hi!
I've just formatted and reinstalled my ubuntu and installed gqrx with apt-get...
It seems that it won't play i/q files anymore (tryed also gqrx from sources).

I usually load my files this way (as i've always done!)

file=/home/freddie/Scrivania/120secondi.raw,freq=7070000,rate=192000,repeat=true,throttle=true

But when i click the start button, gqrx hangs without any error...

Any idea?

**Comment by michelinok** [comment]
Please delete....
My fault....
Very very sorry to have opened a ticket (fight for 3 days, solved after opening the ticket...bad format of new i/q files...)

**Comment by csete** [comment]
No problem :-)
