### ISSUE TITLE
GQRX and SoapySDRServer fail to connect

### ISSUE THREAD

**Issue by thehose** [csete/gqrx#406]
I'm attempting to connect to a remote rtl_sdr dongle running on a SopySDRServer.  It works well when using osmocom_fft with these device strings:

"soapy=0,driver=remote,remote=sdr"
"soapy=0,driver=remote,remote=sdr,remote:driver=rtlsdr"

When I try with gqrx (2.5.3) I does not connect and the server shows no connection attempted. Attached is the conf file used.
[Soapy_RTL_SDR.txt](https://github.com/csete/gqrx/files/462789/Soapy_RTL_SDR.txt)

PS: I have the SoapySDRServer installed and working. I would be glad to run any test's you may need in order to debug this issue.

Hose

**Comment by csete** [comment]
Will try to take a look at it for the 2.7 release. Any more info and data is of course welcome :-)

**Comment by thehose** [comment]
Absolutely, I’ll keep poking around and if anything comes from that I’ll let you know. I’m expecting a LimeSDR at the end of this year (?) and then I’ll switch to that device and put the dongle to eternal rest.

**Comment by csete** [comment]
Hi,

I just tried using SoapySDRServer with the LimeSDR and RTL-SDR and it works. The device string I used was:

> soapy=0,driver=remote,remote:driver=lime

and 

> soapy=0,driver=remote,remote:driver=rtlsdr

respectively.

So, it appears to be working with the latest software.

**Comment by GianisTsol** [comment]
How can i specify the address of the soapyRemoteServer?

**Comment by szpajder** [comment]
`soapy=0,driver=remote,remote=<ip_address_or_hostname>,remote:driver=<remote_driver_name>`
