### ISSUE TITLE
White area on waterfall

### ISSUE THREAD

**Issue by alexf91** [csete/gqrx#410]
There's a white area on the waterfall sometimes.
As far as I can tell, this happens when the number of FFT bins is less than the number of pixels on the waterfall.
![plotter_white_area](https://cloud.githubusercontent.com/assets/2362689/18613879/dc6382a4-7d83-11e6-9688-e28bce97ea92.png)

The white area (and the left over spectrum plot on the right) disappear when I increase the FFT size.

**Comment by csete** [comment]
Hi,

Indeed, there are many situations where drawing artifacts such as this appear when the FFT is zoomed out or dragged beyond the valid range. It can probably be fixed by not allowing zoom or drag beyond the range.
