### ISSUE TITLE
device::find(uhd::device_addr_t const&)' collect2: error: ld returned 1 exit status Makefile:259: recipe for target 'gqrx' failed make: *** [gqrx] Error 1

### ISSUE THREAD

**Issue by stackprogramer** [csete/gqrx#411]
Hi, csete 
my os is debian
i build gnuradio from source, then i install gnuradio, i install gnuradio-osmosdr too,
for option  in your read me:
At least one of:
i installed   RTL-SDR
> Funcube Dongle Pro driver via gnuradio-fcd
> UHD driver via gnuradio-uhd
> Funcube Dongle Pro+ driver from https://github.com/dl1ksv/gr-fcdproplus
> RTL-SDR driver from http://cgit.osmocom.org/cgit/rtl-sdr/
> OsmoSDR driver from http://cgit.osmocom.org/cgit/osmo-sdr/
> HackRF Jawbreaker driver from http://greatscottgadgets.com/hackrf/
i used qmake it has not error...
when i make it :in the end it returns this errors!!!!

tGui -lQtNetwork -lQtCore -lpthread 
/usr/bin/ld: warning: libvolk.so.0.0.0, needed by //usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.7.5, may conflict with libvolk.so.1.3
/usr/lib/x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `uhd::device::find(uhd::device_addr_t const&)'
collect2: error: ld returned 1 exit status
Makefile:259: recipe for target 'gqrx' failed
make: *** [gqrx] Error 1

please help i want to use only rtl-sdr

**Comment by csete** [comment]
Sorry, but this is out of my scope. Try using the packages from the Debian repository.

**Comment by stackprogramer** [comment]
i now unistalled my build gnuradio, now i use apt-get install gnuradio.........
i start to qmake now it has errors 
in make....same before errors...........
/usr/lib/x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `uhd::device::find(uhd::device_addr_t const&)'
collect2: error: ld returned 1 exit status
Makefile:259: recipe for target 'gqrx' failed
make: *** [gqrx] Error 1

**Comment by stackprogramer** [comment]
complete error
/usr/bin/ld: warning: libvolk.so.0.0.0, needed by //usr/lib/x86_64-linux-gnu/libgnuradio-runtime.so.3.7.5, may conflict with libvolk.so.1.3
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `uhd::device::find(uhd::device_addr_t const&)'
Makefile:480: recipe for target 'gqrx' failed
collect2: error: ld returned 1 exit status
make: *** [gqrx] Error 1
00:43:53: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project gqrx (kit: Desktop Qt 5.7.0 GCC 64bit)
When executing step "Make"

**Comment by stackprogramer** [comment]
i finally built it in debian.
https://groups.google.com/forum/#!topic/gqrx/ucwYrS6xtUo
