### ISSUE TITLE
Segfault while starting gqrx 

### ISSUE THREAD

**Issue by W-M-D** [csete/gqrx#412]
Program received signal SIGSEGV, Segmentation fault.
strchr () at ../sysdeps/x86_64/multiarch/../strchr.S:32
32	../sysdeps/x86_64/multiarch/../strchr.S: No such file or directory.

**Comment by csete** [comment]
Sorry, but I can't do anything about it unless you write a proper bug report.

**Comment by W-M-D** [comment]
What information would you like ?

**Comment by W-M-D** [comment]
After building/installing from source it worked fine.

**Comment by csete** [comment]
Minimum info usually includes:

- Operating system, e.g. linux or Mac
- Distribution, e.g. Debian 32 or 64 bit
- Installed from repository, source, or something else
- What SDR hardware is being used

Since you now have it working, do you agree to close the issue?
