### ISSUE TITLE
Zoom cursor is not refreshed when zooming with the mouse

### ISSUE THREAD

**Issue by pyrog** [csete/gqrx#426]
In this example, the zoom is around **1** but the cursor is always at **34x**
![zoom cursor not refresh](https://cloud.githubusercontent.com/assets/2158081/19048032/d5925fea-89a4-11e6-8cff-a0963b8db10d.png)

macOS Sierra
gqrx 2.5.3

**Comment by csete** [comment]
Yeah, the two things are out of sync due to the way they were done historically, but it's such a minor issue that I doubt I will ever have time to fix it.

**Comment by alexf91** [comment]
Looks like I do have time ;-)
#428

**Comment by csete** [comment]
> Looks like I do have time ;-)
> #428

That's great :-)
I'm busy releasing v2.6 this week, but I will take a look at it afterwards.

**Comment by csete** [comment]
Pull request has been merged. Will be available in version 2.7
