### ISSUE TITLE
Connect/disconnect input device when starting/stopping the DSP

### ISSUE THREAD

**Issue by pyrog** [csete/gqrx#427]
When using differents softwares with the same device, it will useful to release it when stopping the DSP.

Example:

1. Run gqrx, looking for a digital signal
1. stop DSP
1. run `rtl_sdr | multimon-ng` from the command line to try to decode it…
1. stop it
1. start DSP…

Currently, I should stop gqrx, do my stuff and restart gqrx.

macOS Sierra
gqrx 2.5.3
Realtek RTL2838UHIDIR 

PS: I know that I could send audio output to UDP and pipe it to multimon but I haven't enough experience yet 😉

**Comment by csete** [comment]
Sorry, but this is not possible in gqrx because gqrx has no control over opening and closing the devices, see issue #384 - significant parts of it would have to be rewritten.
