### ISSUE TITLE
RPi2: after clean install: crash!

### ISSUE THREAD

**Issue by DE8MSH** [csete/gqrx#434]
Hi after clean install and update / upgrade of latest raspian with pixel it does nothing.

This is the result:

http://pastie.org/pastes/10939984/text

After starting GQRX it crashes after press play button.

Stick is R820T2.

What am I missing?

**Comment by DE8MSH** [comment]
Uhm... Solved.

**Comment by DE8MSH** [comment]
Not solved at all. Still same problem as seen above.

**Comment by csete** [comment]
Perhaps the run_gqrx.sh script has been altered since the download?

**Comment by DE8MSH** [comment]
Hi OP Alexandru,

nope. I changed nothing. It's all original after download/install.

**Comment by DE8MSH** [comment]
Hi OP Alexandru,

sometimes it happens :/. I used RPi3 install package instead of RPi2. Will try RPi2 install t'day.

Closed.
