### ISSUE TITLE
Possible typo

### ISSUE THREAD

**Issue by kukabu** [csete/gqrx#438]
Hello

The ";" at the end of the line looks like a bug.
https://github.com/csete/gqrx/blob/master/src/qtgui/plotter.cpp#L1339

**Comment by Cat-Ion** [comment]
Looks like it's just supposed to find the first `level` with `tagEnd[level] <= x`. But the following line should probably be indented better, and maybe replaced by `if(level == nLevels) { level = 0; }` for clarity.

**Comment by kukabu** [comment]
maybe, but I'm embarrassed the indented in next line.

**Comment by csete** [comment]
Fixed by #439

**Comment by kukabu** [comment]
Thank.
