### ISSUE TITLE
Frequency widget digits set to 0 on retune

### ISSUE THREAD

**Issue by ly2ss** [csete/gqrx#445]
(git version)
 Changing frequency 10ths or 100ths MHz sets lesser digits to 0 
I don't know if this is intended feature or some bug.
AFAIR earlier versions behaved different - all lesser digits remained unchanged.
 F.e.: Let's tune to the middle of ham band 14.05MHz and change MHz to 21MHz -  I was used that gqrx tuned to 21.05 but now it's tuned to 21MHz.
 IMHO (as a ham) leaving them unchanged is preferred way,

**Comment by csete** [comment]
Hi @ly2ss 

This was an intended change, so not a bug, sorry.

 Can you try and see if it works out for you? If not, perhaps I can make it a configuration option.

**Comment by ly2ss** [comment]
ok, I'll try to get used to it.

**Comment by csete** [comment]
Ok, but please reopen if you think it's too annoying. I'm sure we can find a way to make it configurable, even if a hidden config value.

**Comment by devnulling** [comment]
IMO it'd be nice to have this as a configurable option with the old method. The new way is usable, but the old way was useful as well. It throws off the causal scanning by adjusting more than what the selected step change is.

**Comment by csete** [comment]
Okay, lets reopen it.

FYI, it is an easy mod if you want to have it locally until we make the change, see commit https://github.com/csete/gqrx/commit/5f7c0177f4d8084a1700284443f3bfd05cc92678 .

**Comment by ly2ss** [comment]
Thanks for mod! Returned back to old behavior. I give my vote for config option too.

**Comment by csete** [comment]
@ly2ss @devnulling 
Can you please check if a manual config record introduced with commit e7f3c94 is sufficient? Thanks.

**Comment by ly2ss** [comment]
Confirming - it's working and sufficient. Thank you.

**Comment by csete** [comment]
Now it is even configurable from the GUI.

**Comment by ly2ss** [comment]
perfect! Thanks!
