### ISSUE TITLE
Bookmarks

### ISSUE THREAD

**Issue by yuvadm** [csete/gqrx#45]
A very nifty feature could be to have bookmarks on arbitrary frequencies, such that a user can:
 - Set a bookmark on a given frequency
 - Have that bookmark show up as a vertical line on both the spectrum and the waterfall
 - Give bookmark a title and a short description to easily mark known frequencies
 - Clicking on viewable bookmarks would set receiver frequency to tune to it

**Comment by csete** [comment]
Bookmarks have been available for a long time, so we can close this issue.
