### ISSUE TITLE
Travis CI

### ISSUE THREAD

**Issue by kukabu** [csete/gqrx#451]
Hello

I think it should be useful to add Travis CI integration.

**Comment by csete** [comment]
I use it for other projects but I'm not sure what added value it would provide for gqrx. Can you elaborate?

In any case, I'm not opposed to it if somebody wants to set it up, but I can imagine the setup would not be trivial with all the dependencies gqrx has.

FYI I run regular coverity scans on gqrx source code:
https://scan.coverity.com/projects/csete-gqrx

**Comment by csete** [comment]
It's now set up and first build passed: https://travis-ci.org/csete/gqrx

**Comment by csete** [comment]
Let me know if there is anything more to do here. As far as I can tell it's all set up now.
