### ISSUE TITLE
ABI compatibility mismatch with UHD library

### ISSUE THREAD

**Issue by stephensworld** [csete/gqrx#454]
Hi,

I have a problem when opening gqrx application.

<img width="667" alt="bildschirmfoto 2016-11-21 um 01 07 03" src="https://cloud.githubusercontent.com/assets/15073276/20467386/fbcc6cde-af86-11e6-8329-a99f71795f54.png">

Maybe someone could help me.

Thanks
Stephan

**Comment by csete** [comment]
You probably have a mixture of packages installed from source and from binary repositories, which almost always leads to conflicts at runtime. I also note that you run gqrx as root; please don't do that!

**Comment by csete** [comment]
It could also be that you have everything built from source, but you have upgraded UHD after you have built gnuradio and so the versions mismatch.

**Comment by simontudo** [comment]
Same error here. I installed everything following [this guide](http://gqrx.dk/download/install-ubuntu) on a clean Ubuntu 16.04 installation. Nothing built from source, everything from PPA.

**Comment by csete** [comment]
It looks like the UHD packages have been upgraded from 3.10.0.0 to 3.10.1.0 and this breaks binary compatibility with our packages. We have to rebuild the gnuradio packages, so stay tuned.

**Comment by csete** [comment]
Hi guys,

There should be a new build of gnuradio available: 3.7.10.1-1~ubuntu16.04.1myriadrf2
It should appear as an update in your package manager.

I'm not sure if we also have to rebuild gr-osmosdr and I'm away from my dev computers, so can you please try it and see if it resolves the error?

Thanks!

**Comment by simontudo** [comment]
Hey, 
I just updated the sources and installed the upgrades and everything works fine! Thank you very much!

**Comment by csete** [comment]
Sounds great - thanks for reporting back!
