### ISSUE TITLE
Recording file (.wav) size

### ISSUE THREAD

**Issue by sv1** [csete/gqrx#460]
On Gqrx 2.6, when I make a recording of the audio, the .wav file size is increasing although the squelch is closed.

**Comment by starvald** [comment]
You can use gqrx-scan, it will record a file when a signal is detected.

**Comment by csete** [comment]
This is how it works today. Issue #109 concerns adding squelch triggered audio recording.

**Comment by csete** [comment]
Hi @sv1, perhaps you can add your wishes to issue #109, if not already covered there, and we can close this one to avoid duplicates?

**Comment by sv1** [comment]
Please close this!!!
