### ISSUE TITLE
Scan active frequencies

### ISSUE THREAD

**Issue by yuvadm** [csete/gqrx#47]
While monitoring a certain frequency that includes several nearby channels, it could be awesome to have an option to scan them:

 - Define a group of receivable channels in the current frequency range (by receiver offset)
 - Set an arbitrary order on selected channels
 - Automatically tune receiver to first channel in set that is active (above squelch level)

I would like to take a stab at implementing this myself. I'm assuming the GUI is the easy part. Basically, I need a hook that allows me to inspect the signal after passing through FFT, determine if any of the selected channels are above squelch, and if so, set the receiver frequency to that channel.

Any pointers to places in the code I want to look at would be awesome.

**Comment by Harvie** [comment]
There is perl script that can scan frequencies using gqrx:
https://github.com/khaytsus/gqrx-scan
It probably has all functionality needed. Maybe you can use it. However it uses gqrx remote control...

**Comment by csete** [comment]
Indeed, gqrx-scan does the job and I don't have any plans for adding a built-in scanner anytime soon.

**Comment by ukoda** [comment]
I have already done a scanner that works from the spectrum view output.  It works really well, changing frequency in near real-time, and looks for either the most recent or strongest signal.  It will ignore static carrier signals that would stop a conventional scanner.  The main reason I have not done a pull request is I wanted to improve the related GUI.  Maybe I should hard code some settings for now and leave the extra GUI configuration settings for later.  The version I forked is a bit out of date now so I would also need to do a rebase before doing a pull request.  My fork is at https://github.com/ukoda/gqrx but can't recall if I have pushed my most recent work from my workstation.  In the process of creating and testing it I have learned a lot so my code could probably be improved.

**Comment by csete** [comment]
My priorities at this time are to make gqrx stable, smaller and faster, and to reduce the maintenance burden so that I can also spend time on other projects. That doesn't rule out adding new functionality, but I want to be part of the definition and design process of anything that alters the program in a significant way.

**Comment by ukoda** [comment]
Sure.  In mainwindow.cpp there is a loop to "Normalize, calculate power and shift the FFT" which my changes add a lot of extra code to do what I wanted to achieve.  I did worry it may not be welcomed by people who did not want that functionality or trying to run on lean systems.  I''m working on another project now but I will come back to this and get it suitable for a pull request.  At that point you can accept changes, make suggestions on redesign, or I can just leave as a fork.  Before I do a pull request I can create some documentation to describe what I did and why.

I had a chance to try it in busy area on a recent trip to the USA and was also able to record some I/Q data for future testing.  What l like about using the FFT data to control the scanner is it is so fast you catch the start of transmissions where as a conventional scanner watching 40+ channels can lose severals seconds of a transmission.  Also it centers the demodulator on the center of the transmission so you can see how far off frequency each transmitter is.
