### ISSUE TITLE
Auto-tuning through remote control may need tweaking

### ISSUE THREAD

**Issue by csete** [csete/gqrx#471]
https://groups.google.com/d/msg/gqrx/e7BuIWJ7W1w/vSwmIcGRDAAJ

@kukabu if you have time you are welcome to see if there is anything we need to tweak here.

**Comment by kukabu** [comment]
Hello

I think I can fix it but only after holidays.

**Comment by csete** [comment]
Sounds great. No hurry from my part. Enjoy your holidays!
