### ISSUE TITLE
Audio mixer

### ISSUE THREAD

**Issue by Arinerron** [csete/gqrx#479]
Can we have a built-in software-based audio mixer too? It would be perfect in the `Tools` menu.

**Comment by LongnoseRob** [comment]
May I ask which signals this mixer should be able to use?

What makes an internal mixer better then external programs like pavucontrol or alsa-mixer cannot do?

**Comment by csete** [comment]
I would also like to know what this mixer should mix, since there is only on source that produces audio in gqrx.

**Comment by csete** [comment]
Ok, I guess this was just some noise. If not, feel free to reopen and provide the necessary details.
