### ISSUE TITLE
crash at start. 

### ISSUE THREAD

**Issue by gogomartin** [csete/gqrx#488]
I've compiled SoapySDR, LimeSuiteGUI and gqrx on a Kali Linux (Lenovo laptop)

I had a coupple of issuses getting it to complie. I finally got it to compile, gqrx finds the LimeSDR-USB, but it crashes during start with the output below.

Any suggestions?

Thanks! 

gr-osmosdr v0.1.4-77-g2a2236cc (0.1.5git) gnuradio 3.7.10
built-in source types: file fcd rtl_tcp rfspace soapy redpitaya 
Resampling audio 96000 -> 48000
BookmarksFile is /root/.config/gqrx/bookmarks.csv
gr-osmosdr v0.1.4-77-g2a2236cc (0.1.5git) gnuradio 3.7.10
built-in source types: file fcd rtl_tcp rfspace soapy redpitaya 
[INFO] Make connection: 'LimeSDR-USB [USB 2.0] 9060B00472922'
Estimated reference clock 30,7196 MHz
Selected reference clock 30,720 MHz
[INFO] Device name: LimeSDR-USB
[INFO] Reference: 30,72 MHz
[INFO] Init LMS7002M(0)
LMS7002M values cache at /root/.limesuite/LMS7002M_cache_values.db
[INFO] Ver=7, Rev=1, Mask=1
[INFO] LMS7002M calibration values caching Enable
[INFO] SoapyLMS7::setFrequency(Rx, 0, BB, 0 MHz)
[INFO] SoapyLMS7::setFrequency(Tx, 0, BB, 0 MHz)
[INFO] SoapyLMS7::setAntenna(Rx, 0, LNAL)
[INFO] SoapyLMS7::setAntenna(Tx, 0, BAND1)
[INFO] SoapyLMS7::setGain(Rx, 0, PGA, 0 dB)
[INFO] SoapyLMS7::setGain(Rx, 0, LNA, 0 dB)
[INFO] SoapyLMS7::setGain(Rx, 0, TIA, 0 dB)
[INFO] SoapyLMS7::setGain(Tx, 0, PAD, -50 dB)
[INFO] SoapyLMS7::setSampleRate(Rx, 0, 10 MHz), CGEN=80 MHz, ADC=20 MHz, decim=2
ConnectionSTREAM::ConfigureFPGA_PLL(tx=20MHz, rx=10MHz)
[INFO] SoapyLMS7::setSampleRate(Tx, 0, 10 MHz), CGEN=80 MHz, DAC=20 MHz, interp=2
ConnectionSTREAM::ConfigureFPGA_PLL(tx=10MHz, rx=10MHz)
[INFO] SoapyLMS7::setBandwidth(Rx, 0, 30 MHz)
[INFO] Rx Filter calibrated from cache
[INFO] SoapyLMS7::setBandwidth(Tx, 0, 30 MHz)
[INFO] Tx Filter calibrated from cache
[INFO] SoapyLMS7::setFrequency(Rx, 1, BB, 0 MHz)
[INFO] SoapyLMS7::setFrequency(Tx, 1, BB, 0 MHz)
[INFO] SoapyLMS7::setAntenna(Rx, 1, LNAL)
[INFO] SoapyLMS7::setAntenna(Tx, 1, BAND1)
[INFO] SoapyLMS7::setGain(Rx, 1, PGA, 0 dB)
[INFO] SoapyLMS7::setGain(Rx, 1, LNA, 0 dB)
[INFO] SoapyLMS7::setGain(Rx, 1, TIA, 0 dB)
[INFO] SoapyLMS7::setGain(Tx, 1, PAD, -50 dB)
[INFO] SoapyLMS7::setSampleRate(Rx, 1, 10 MHz), CGEN=80 MHz, ADC=20 MHz, decim=2
ConnectionSTREAM::ConfigureFPGA_PLL(tx=20MHz, rx=10MHz)
[INFO] SoapyLMS7::setSampleRate(Tx, 1, 10 MHz), CGEN=80 MHz, DAC=20 MHz, interp=2
ConnectionSTREAM::ConfigureFPGA_PLL(tx=10MHz, rx=10MHz)
[INFO] SoapyLMS7::setBandwidth(Rx, 1, 30 MHz)
[INFO] Rx Filter calibrated from cache
[INFO] SoapyLMS7::setBandwidth(Tx, 1, 30 MHz)
[INFO] Tx Filter calibrated from cache

FATAL: destination port 1 out of range for source_impl(47)

Trying to fill up 18446744073709551615 missing channel(s) with null source(s).
This is being done to prevent the application from crashing
due to gnuradio bug #528.

terminate called after throwing an instance of 'std::invalid_argument'
  what():  destination port 2 out of range for source_impl(47)
Avbruten (SIGABRT)

**Comment by csete** [comment]
Some sample rate and bandwidth settings cause the program to crash. Use either 0 MHz or 60 MHz, the latter for HF. There are more tips and tricks on the [forum](https://discourse.myriadrf.org/).

If you have more question or problems please either use the [gqrx mailing list](https://groups.google.com/forum/#!forum/gqrx) or the [myriadrf forum](https://discourse.myriadrf.org/) (for limesdr) and keep [github for development](http://gqrx.dk/user-support) work, thanks.
