### ISSUE TITLE
Buffer fill up FFT latency

### ISSUE THREAD

**Issue by KC7NOA** [csete/gqrx#498]
Im not sure where this issue is located ...

I know that when set to FM and ran for a while that the latency for the FFT and audio playback gets real long ... almost 10 seconds delayed (more?)

Quickest way to get back to real time is to simply stop gqrx and start again.

Sorry if this has already been expressed .... im not sure exactly how to discribe it.

Odroid-C2/Ubuntu16 , all built from git

**Comment by csete** [comment]
It could be that the odroid can not keep up at that sample rate and one of the blocks (probably FM demod) runs slower and builds up the latency. You can check using a tool like htop - it should show 1 core running at close to 100%.

Please note that the preferred channel for user support is the mailing list, see http://gqrx.dk/user-support, and we only use github as a developer tool.

**Comment by csete** [comment]
By the way, did you run the volk_profile tool?

**Comment by KC7NOA** [comment]
Im not 100% sure i did on the C2 ... I have before ...

And it will be a easily be a few days before i can check .. i have taken the setup apart to try to find a suitable case for the Odroid and LimeSDR. That i dont need to cut a bunch of holes into.

**Comment by csete** [comment]
No problem, just post when you have update.

**Comment by csete** [comment]
Any updates here? If not, we should close this.
