### ISSUE TITLE
FFT view is flat

### ISSUE THREAD

**Issue by pointhi** [csete/gqrx#502]
For LimeSDR support, I recompiled soapysdr, gr-osmosdr as well as gqrx on arch linux with the normal packages. But now, the FFT view doesn't work anymore. The waterfall display on the other side works, as well as the audio output.

It's no LimeSDR specific problem. A normal RTL-SDR shows the same view

![qgrx_with_no_fft](https://cloud.githubusercontent.com/assets/1652144/24308165/41da63a6-10c7-11e7-8ed0-fd177ee5a1c2.png)

**Comment by alexf91** [comment]
This issue doesn't seem to go away...
Try starting with `gqrx -r`

**Comment by pointhi** [comment]
thanks, now it works
