### ISSUE TITLE
Feature request: Audio waterfall

### ISSUE THREAD

**Issue by Keziolio** [csete/gqrx#505]
It would be cool to have another waterfall, maybe horizontal, for the decoded audio

**Comment by alexf91** [comment]
There's already a waterfall view for audio, you just need to enable it:

![screenshot_2017-03-28_11-11-43](https://cloud.githubusercontent.com/assets/2362689/24397790/95e64888-13a7-11e7-86f8-4ee74c977e1d.png)

**Comment by Keziolio** [comment]
Cool,
I got confused with the different UI for the settings (button vs tab)

So this issue can be closed,
Thanks
