### ISSUE TITLE
Feature request: WIFI analyser using ath9 framework

### ISSUE THREAD

**Issue by kellogsgit** [csete/gqrx#509]
First, I would like to thank you for the hard work.

I would like to point out the community ath9 WIFI spectrum scanning feature:
https://wireless.wiki.kernel.org/en/users/drivers/ath9k/spectral_scan

I am using a TP-LINK CPE210, which includes 2.4Ghz radio and enough space for LEDE embedded device. This device is only around 40 EUR in France. Here is a photo of the device:
https://images-na.ssl-images-amazon.com/images/I/41x4DZHBSPL._SL1000_.jpg

Here is the link to LEDE installer for CPE210:
https://lede-project.org/toh/hwdata/tp-link/tp-link_tl-cpe210_1

Once LEDE is installed, you can connect using SSH to the CPE210.
I can confirm that CPE210 supports spectrum analysis in the 2.4 Ghz band.

Do you think the ath9 spectral analyser could be supported in gqrx. Of course, there is no radio or sound to listen to. This is only for spectral analysis.

Does it make sense?

**Comment by csete** [comment]
Hi,

Gqrx is basically just a GUI with some DSP routines. Device support is handled by external libraries, namely gr-osmosdr or SoapySDR. Support for new devices is added through either of these libraries.

Also note that gqrx requires raw I/Q samples for further signalprocessing, whereas this device provides only FFT data. So, I think this is outside the scope of gqrx.
