### ISSUE TITLE
Tooltips are black on black in the mainwindow

### ISSUE THREAD

**Issue by chron-isch** [csete/gqrx#512]
Hi,

thanks for all the work, I love the program!

It's not really a bug and shouldn't cause you much work, but it's one of my mayor pet peeves with gqrx.
On my system (ArchLinux) the tooltips in the mainwindow showing the FFT and waterfall are black on black, which makes them almost impossible to read.

Apparently they get their color from setting `background-color: rgb(31, 29, 29);` in the Stylesheet of centralWidget  in mainwindow.ui

Creating a new Stylesheet for plotter with `QToolTip { background-color: #FFFFDD; }` fixes it, or at least makes the tooltips readable again. I have no clue how to tell QT to use its default tooltip style...

Alex

**Comment by alexf91** [comment]
Arch is always fun to fix bugs ;-)
Which windowmanager are you using?

**Comment by chron-isch** [comment]
i3.

**Comment by alexf91** [comment]
Of course something strange^^
Maybe I'll find some time too look into it. I have essentially the same problem with Qtile.

**Comment by csete** [comment]
On my computer it uses the system default (white text on black background)

**Comment by chron-isch** [comment]
Like I said, I fixed it for myself by just adding `QToolTip { background-color: #FFFFDD; }` to the CPlotter stylesheet, but I really would like to figure out how to get it to just use the QT default settings.

**Comment by LongnoseRob** [comment]
I had the same issue with unreadable tooltips on Arch w/ XFCE.

@chron-isch  you could try qt5ct (https://www.archlinux.org/packages/?name=qt5ct)
also helpful was reading https://wiki.archlinux.org/index.php/Qt#Configuration_of_Qt5_apps_under_environments_other_than_KDE_Plasma

**Comment by csete** [comment]
FYI I set the background color of the centralWidget to rgb(31, 29, 29) - I wonder if that has any impact for you. It makes no difference for tooltips on my xfce.

**Comment by chron-isch** [comment]
@csete That's excatly what I was thinking as well.

Screenshot: https://paste.xinu.at/WFW/

**Comment by LongnoseRob** [comment]
@chron-isch after installing and running qt5ct (setting the colors you`d like), you need to set environment variable QT_QPA_PLATFORMTHEME=qt5ct, and then run gqrx.

**Comment by chron-isch** [comment]
```
chron@censored # env | grep QT
QT_QPA_PLATFORMTHEME=qt5ct
```
Yep :)

**Comment by LongnoseRob** [comment]
@chron-isch strange.. maybe i3wm is doing things different from the way xfce is doing

**Comment by csete** [comment]
Which version of Qt are we talking about? There have been some changes from 5.6 to 5.7 regarding Qt themes. Qt 5.6 with xfce looks just fine; however, 5.7 and later looks like windows 95 unless I explicitly set the theme with "-style fusion" or something like that.

**Comment by chron-isch** [comment]
qt5 5.8.0

**Comment by csete** [comment]
So, I have built it with Qt 5.8 and have the same issue.

**Comment by karstengit** [comment]
Hello gods of GQRX.
I have compiled GQRX V 2.6 for Debian stable and i have the same problem here.

Maybe the problem is caused in KDE by the used schema, but this problem occurs only in this application!
So how can i fix it?

I am not familiar with QT programming and i could not make the modifications as suggested, because they are not complete.
I tried it but i does not work!
@chron-isch : Please give a complete alternate file to compile!

This additional informations are a good new feature - but it is unusable now.
Please help to solve the problem.

**Comment by remicles** [comment]
I had the same dark tooltips over waterfall and spectrum.  Linux Mint 17.1, Qt 5.2.1, GQRX v2.6-111-g82e0cc2.
This worked for me:
`export QT_STYLE_OVERRIDE=gtk`
Makes everything else look better too, IMO.

**Comment by karstengit** [comment]
Thanks remicles.
This export really fix the problem.
```export QT_STYLE_OVERRIDE=gtk```

So there should be a fixed style for gqrx V 2.6

**Comment by chron-isch** [comment]
@karstengit Sorry for the late reply, here's the patch im currently using:
```
--- src/gqrx-2.6.1/src/applications/gqrx/mainwindow.ui	2017-02-16 20:40:14.000000000 +0100
+++ src_mod/gqrx-2.6/src/applications/gqrx/mainwindow.ui	2017-04-23 00:49:58.702910208 +0200
@@ -153,6 +153,9 @@
         <verstretch>0</verstretch>
        </sizepolicy>
       </property>
+      <property name="styleSheet">
+       <string notr="true">QToolTip { background-color: #FFFFDD; }</string>
+      </property>
       <property name="frameShape">
        <enum>QFrame::StyledPanel</enum>
       </property>
```
But it's more of a workaround, since it just sets the background-color to something readable and not the default color every other tooltip uses.

**Comment by stujones11** [comment]
Same here with debian 9, however, the workaround posted be @karstengit does fix the problem for me.

**Comment by chyard** [comment]
Just wanted to thank everyone for this thread. Having the unreadable tooltips was a frustration. I tried all of the above env-based workarounds with no joy (Parrotsec current), but @karstengit's code patch solved the issue nicely. That's what open source is all about. Cheers.

**Comment by dtwooton** [comment]
Here is a way to change the foreground

[tool_color.txt](https://github.com/csete/gqrx/files/1752642/tool_color.txt)

**Comment by csete** [comment]
It's fixed and will be available in the next version / build!

**Comment by tomswartz07** [comment]
Thanks @csete! I forgot how much I liked the tooltips, now that I can read them :)
