### ISSUE TITLE
very high cpu usage on OS X

### ISSUE THREAD

**Issue by cissusnar** [csete/gqrx#517]
![2017-05-06 12 54 41](https://cloud.githubusercontent.com/assets/2087003/25755761/c55c8ba0-31f6-11e7-8df3-81bb43a97c3c.png)

**Comment by csete** [comment]
I'm not sure why you opened this issue, I most certainly doubt anybody can do anything based on the info you provide. CPU load depends on many factors and 290% is not necessarily much.

Please see http://gqrx.dk/user-support
