### ISSUE TITLE
Connect() loop silently failing with unreachable rtl_tcp address

### ISSUE THREAD

**Issue by martymac** [csete/gqrx#519]
Hi,

When using a rtl_tcp device string with an IP address that is not reachable (or where no rtl_tcp server is listening), gqrx seems to fall down to an infinite connect() loop which is silently failing.

Tracing the process shows the following error :

 2537: connect(12,{ AF_INET6 [::1]:1234 },28)    ERR#61 'Connection refused'
 2537: connect(12,{ AF_INET6 [::1]:1234 },28)    ERR#61 'Connection refused'
 2537: connect(12,{ AF_INET6 [::1]:1234 },28)    ERR#61 'Connection refused'
 2537: connect(12,{ AF_INET6 [::1]:1234 },28)    ERR#61 'Connection refused'
[...]

I am using gqrx 2.6.1 on FreeBSD.

Thanks for your help,

Regards,

Ganael.

**Comment by erikarn** [comment]
heh, I /just/ went through this with him! heh

**Comment by martymac** [comment]
Great, thanks!

**Comment by csete** [comment]
Don't know if you found the workaround, but it's in #518

**Comment by csete** [comment]
Also, as I wrote in the other thread, the rtl_tcp interface in the official gr-osmosdr library is broken, so you will have to use my fork if you want to use rtl_tcp: https://github.com/csete/gqrx/issues/518#issuecomment-299742895

By the way, why do you want to use rtl_tcp on the same machine? Is there a problem with USB device access on FreeBSD?

**Comment by martymac** [comment]
Thanks for the workaround in bug #518.

No, I have no problem with direct access to a local USB device, it works fine. I was just trying to reproduce bug #518 but was not aware of the fact that it had already been submitted (I got the bug through another channel).

Sorry for the noise... and thanks for developping Gqrx !

**Comment by erikarn** [comment]
Oh, just wanting to get it working right first before i indeed use remote
rtl_tcp instances.


-a

**Comment by csete** [comment]
Hey, no problem. I realize it can be difficult to know where a problem occurs since there are so many layers between gqrx and the hardware.
