### ISSUE TITLE
Auto-squelch sets to 0.0 dB too often.

### ISSUE THREAD

**Issue by tnadolecki** [csete/gqrx#520]
Hi,
Very often "A" button sets squelch to 0.0 dB, no signals go thru this strong...
A video demonstrating the problem. https://www.youtube.com/watch?v=Zo2VQr-KYhA
Thanks.
T.

**Comment by csete** [comment]
Thanks for the demo. I have seen this occasionally but didn't know if it is an issue. We better take a look at it some time.

**Comment by csete** [comment]
Hello,

I have tried to improve this. If the measure power is above -90 dBFS, we keep the current one. I hope this will be sufficient.
