### ISSUE TITLE
Segmentation fault fresh build

### ISSUE THREAD

**Issue by caipiblack** [csete/gqrx#521]
Dear guys,

I have rebuild and install from sources gnuradio, gr-osmosdr, gqrx ..

All the build is successful.

But now when I start gqrx, i get into a segmentation fault:

`caipiblack@caipiblack-pc-ubuntu:~/rtl_sdr/gqrx.git/build$ ./gqrx
gr-osmosdr v0.1.4-98-gc653754d (0.1.5git) gnuradio 3.7.12git-156-g54e89c64
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy redpitaya 
Erreur de segmentation (core dumped)
caipiblack@caipiblack-pc-ubuntu:~/rtl_sdr/gqrx.git/build$`

Did someone build gqrx with fresh libraries recently ? 

Probably next week I will have some time for debug the software and check where it generate the fault.

**Comment by csete** [comment]
What you call "fresh libraries" seem to be arbitrary snapshots from developers git repository, so this sounds more like a topic for a developer forum and not a bug report.
