### ISSUE TITLE
Feature Request: Remote Control LNA Gain

### ISSUE THREAD

**Issue by hosler** [csete/gqrx#524]
I would like to be able to control my dongle's gain via remote control

**Comment by csete** [comment]
We can take a look, but I 'm not sure how to handle this. Different devices have different type of gain settings.

**Comment by danhosler** [comment]
only toggling the gain on/off might be easier if you need to accommodate all devices.

**Comment by alexf91** [comment]
I've started working on this.
I'll expose it through the "level" command (l, L) and call the different gain settings <GAIN_NAME>_GAIN.

**Comment by csete** [comment]
What I was trying to say is that different devices have different gain names, so the TCP client would need to know which gains are available. Then suddenly we have data flow from gr-osmosdr to a TCP client - sounds like a bad idea...

**Comment by alexf91** [comment]
I haven't really thought about the client side, but the available gain names can be queried by using the "l ?" command and filtering the return values for "_GAIN".

**Comment by csete** [comment]
PR #635 merged and will be available in 2.12.
