### ISSUE TITLE
Cross compile error with Raspberry pi 3

### ISSUE THREAD

**Issue by hanzzery** [csete/gqrx#531]
Hello,
 I download the GQRX source with raspberry pi 3.
 when I compiled, displayed error message is "cross compiling with out sysroot. Disabling pkg-config" and "gnuradio-audio development package not found"
Please find its solution.
Thank you in advance.

**Comment by csete** [comment]
This is a bug tracker, not a help desk. Please see http://gqrx.dk/user-support
