### ISSUE TITLE
gqrx crash when demodulating wideband fm (mono/stereo/oirt) all other modes work

### ISSUE THREAD

**Issue by mayorbobster** [csete/gqrx#533]
Hello.  Just re-installed gnuradio and gqrx.  Made gqrx with qt-5
I did not have to make any changes to gqrx/gnuradio source (w.r.t. pulseaudio)
gnuradio sources (gnuradio/cheetah/gr-osmosdr/rtlsdr/swig) are all from github
gqrx is from github
cmake is from github
operating system and nouveau video drivers are from github
Base system is linux mint 18.2
AM/NFM/USB all work ok
I have attached a crash dump

The build script I used for gqrx is:
#!/bin/bash
#
# nice to have for gnuradio
 apt-get -y install qt4-qmake
 apt-get -y install qt5-qmake
 apt-get -y install libqt5svg5-dev
 apt-get -y install qtbase5-dev-tools
 apt-get -y install qtbase5-dev

SRCDIR=gqrx.git

CORES=`cat /proc/cpuinfo | grep siblings | tail -1 | tr -s ' ' | sed 's,.*: ,,'`

if [ ! -d $SRCDIR ]
then
git clone https://github.com/csete/gqrx.git $SRCDIR
cd $SRCDIR
else
cd $SRCDIR
git pull
fi

if [ ! -d build ]
then
mkdir build
else
rm -rf build
mkdir build
fi

cd build
qmake -qt5 ..

./configure
make -j $CORES
# make check
make install 

Crash Dump:

[gqrx.bug.txt](https://github.com/csete/gqrx/files/1202742/gqrx.bug.txt)

Thank You.

**Comment by csete** [comment]
Sorry, but  since you are using untested daily snapshots from the gnuradio git repository you are on your own.

If you want to use gqrx, please use well tested and officially released versions. And please do not run gqrx as root.
