### ISSUE TITLE
Port Mismatch with GPREDICT

### ISSUE THREAD

**Issue by vk4tec** [csete/gqrx#544]
I was debugging a connection issue between gpredict and gqrx

The gqrx website and software says use port 7356 

http://gqrx.dk/doc/remote-control

When I run up gpredict it is hard coded to port 4532

I used wireshark on localhost to spot this port mismatch

Can we align the two as to not confuse people

I am writing a gpredict to ICOM CIV program 

Andrew VK4TEC

**Comment by vk4tec** [comment]
MacBook:src vk4tec$ grep 4532 *
grep: nxjson: Is a directory
sat-pref-rig-editor.c:    gtk_spin_button_set_value(GTK_SPIN_BUTTON(port), 4532);
sat-pref-rig-editor.c:        gtk_spin_button_set_value(GTK_SPIN_BUTTON(port), 4532); /* hamlib default? */
sat-pref-rig-editor.c:    gtk_spin_button_set_value(GTK_SPIN_BUTTON(port), 4532);     /* hamlib default? */
sat-pref-rig.c:        .port = 4532,
sat-pref-rig.c:        .port = 4532,
sat-pref-rig.c:        .port = 4532,
grep: sgpsdp: Is a directory

**Comment by csete** [comment]
The gqrx website says "By default gqrx is configured to accept connections from the localhost on port 7356" 

You can use whatever port you want.
