### ISSUE TITLE
gqrx version 2.6 on MacBook no audio on Mode USB LSB CW ( other than FM )

### ISSUE THREAD

**Issue by vk4tec** [csete/gqrx#545]
I was having issues not getting any audio out on my MacBook Pro with gqrx 2.6 when I operated in USB LSB CW modes.

I toggled the AGC setting in gqrx to slow and then audio was immediately heard

The signal strength was the same on RF.

It seemed to not pipe or mute the audio when the mode was set to something other than FM unless the AGC in gqrx receiver options is set to something other than OFF

Andrew VK4TEC Aug 2017

**Comment by csete** [comment]
I'm not sure what you are trying to report here. I don't think there is any bug here. When AGC is OFF you are supposed to adjust manual gain under advanced AGC settings, otherwise the audio level will be very low.
