### ISSUE TITLE
gqrx: symbol lookup error: /usrb/x86_64-linux-gnu

### ISSUE THREAD

**Issue by sikongsima** [csete/gqrx#546]
**error：**gqrx: symbol lookup error: /usrb/x86_64-linux-gnubgnuradio-uhd.so 
.3.7.10: undefined symbol: _ZN3uhd4usrp10multi_usrp7ALL_LOSB5cxx11E
Installation successful，but function gqrs have a error，installed in accordance with official instructions

**Comment by csete** [comment]
This is not a bug but a well known installation error and you can find the answer if you search the web. If you need further assistance, please see http://gqrx.dk/user-support
