### ISSUE TITLE
GQRX crashed at startup

### ISSUE THREAD

**Issue by F0FYF** [csete/gqrx#548]
Hi
I have gqrx on a xubuntu 16.04. I have install it by the source code. Everything allright, no compilation error but when i want to start it, i have this : 

jeff@Radio:~/hamradio/gqrx.git$ gqrx
linux; GNU C++ version 5.4.0 20160609; Boost_105800; UHD_003.010.002.000-0-gbd6e21dc

gr-osmosdr v0.1.4-98-gc653754d (0.1.5git) gnuradio 3.7.11.1
built-in source types: file fcd rtl rtl_tcp uhd hackrf bladerf rfspace airspy redpitaya 
Resampling audio 96000 -> 48000
BookmarksFile is /home/jeff/.config/gqrx/bookmarks.csv
*** Error in `gqrx': free(): invalid pointer: 0x0000000002687230 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7ff429c5b7e5]

/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7ff429c6437a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7ff429c6853c]
/usr/local/lib/libgnuradio-runtime-3.7.11.1.so.0.0.0(_ZN2gr5blockD1Ev+0xdf)[0x7ff42bdb1daf]
.....
7ff42cd07000-7ff42cd08000 rw-p 000eb000 08:01 4071546                    /usr/local/lib/libgnuradio-filter-3.7.11Abandon (core dumped)

Any idea ? 
Thanks for the help

Jeff

**Comment by csete** [comment]
In general I do not support source installations (I really need to draw a line on what I spend my time on). However, you are not the first one to report issues with gnuradio 3.7.11 so for now I would recommend using 3.7.10 as that is the one we have tested.

I would also kindly ask you to follow http://gqrx.dk/user-support and use the mailing list for user support and keep github issues for tracking bugs and feature requests.
