### ISSUE TITLE
gqrx crashes on airspy mini at 2.5 MHz sample rate

### ISSUE THREAD

**Issue by vk4tec** [csete/gqrx#551]
Not sure if you can code this out 

Airspy Mini - it was crashing sometimes 

I found out it is when the sample rate was set to 2.5 MHz

The mini can only do 3,6 and 10 i think it is

Andrew

**Comment by csete** [comment]
Gqrx can not see whether it is an Airspy R2 or a mini. Therefore, as the [website says](http://gqrx.dk/supported-hardware#airspy), the user must select the correct sample rate according to device type (Airspy R2 or Mini).
