### ISSUE TITLE
text label for recoding file

### ISSUE THREAD

**Issue by ghost** [csete/gqrx#552]
Would it be possible please to add a label to the form 

That shows the recording file when you hit "rec" in the audio form 

Any chance of a size of file ?

Andrew

**Comment by csete** [comment]
Sorry, but I do not understand what you are asking for.

**Comment by alexf91** [comment]
I think he means the label below the controls in the audio dock widget.
The current filename is displayed when a file is played, but not when it's recorded.

**Comment by csete** [comment]
I suppose we could do that.

**Comment by argilo** [comment]
This was implemented in #913.
