### ISSUE TITLE
No audio on MacBook Pro V2.6

### ISSUE THREAD

**Issue by vk4tec** [csete/gqrx#553]
When I have my computer set to AM and SLOW AGC it works fine.

I tuned to a broadcast station and let the AGC rise.

As soon as i set the AGC to OFF there was a squelch affect with no audio at all

The Squelch was set to -153 

Unless I set the AGC to something other than OFF I get no Audio 

This is wrong.

With no AGC I should at least get static

I get nothing 

Andrew

**Comment by csete** [comment]
Like I have already explained to you in issue #545, if you switch AGC OFF you have to adjust the "Gain" under advanced AGC settings. The default value is 0 dB, which in most cases will give a very low audio level and you can not hear anything.

Please don't open any more issues about this!
