### ISSUE TITLE
include conflict : cmath vs math.h

### ISSUE THREAD

**Issue by jan2son** [csete/gqrx#557]
I can't build sources (master branch, commit SHA 9648a14).
There is obviously include issue :

../qtgui/plotter.cpp: In member function ‘void CPlotter::drawOverlay()’:
../qtgui/plotter.cpp:1168:39: error: call of overloaded ‘abs(double)’ is ambiguous
     m_dBStepSize = abs(m_MaxdB-m_MindB)/(double)m_VerDivs;

It seems the qtgui/plotter.cpp includes some header whch includes with math.h . Maybe Makefile order could solve this issue.

I am using standard ubuntu 17.04, 
g++ -v
  gcc version 6.3.0 20170406 (Ubuntu 6.3.0-12ubuntu2)

make -v
  GNU Make 4.1
  Built for x86_64-pc-linux-gnu

**Comment by csete** [comment]
> I can't build sources (master branch, commit SHA 9648a14).

That commit is from October 2014. Sorry but I have more than enough things to do already and don't see why we should be concerned about this.

**Comment by jan2son** [comment]
Thank you! I will check latest commit.

**Comment by jan2son** [comment]
I did use a wrong repository.
