### ISSUE TITLE
UDP host setting does not persist

### ISSUE THREAD

**Issue by yuvadm** [csete/gqrx#559]
When changing the UDP host setting from anything that isn't `localhost` the setting doesn't persist after program exit, it probably should.

My current workaround is to manually add `udp_host=127.0.0.1` to `default.conf` (needed because `localhost` UDP packets don't arrive for some reason).

**Comment by csete** [comment]
It only happens with 127.0.0.1 - other IP addresses of host names work fine.

You can change the code here if you want:
https://github.com/csete/gqrx/blob/master/src/qtgui/dockaudio.cpp#L330

**Comment by yuvadm** [comment]
Any reason it's excluded specifically?

**Comment by csete** [comment]
Only that localhost and 127.0.0.1 are the same default and by principle we do not save the default value. I will change this but I have just shipped v2.8 yesterday so it will be a while before I will make a new release.

**Comment by yuvadm** [comment]
@csete Thanks for the fix!

**Comment by csete** [comment]
@yuvadm thanks for the feedback - I take it it solved your problem then :)

**Comment by yuvadm** [comment]
Haven't tested yet, but looks like it should
