### ISSUE TITLE
Please provide RPi 3 downloads for versions 2.7, 2.8 (GH releases)

### ISSUE THREAD

**Issue by Sciss** [csete/gqrx#562]

**Comment by csete** [comment]
I hate to disappoint you but opening an issue about it is not going to produce binaries for the raspberry pi.

**Comment by Sciss** [comment]
I don't understand - What is the problem with adding binaries to the releases page? The last one is for 2.6, skipping 2.6.1, 2.7, 2.8? Is this not working any longer on the Pi?

**Comment by csete** [comment]
> What is the problem with adding binaries to the releases page?

The binaries do not exist. When they exist, they will be added to the download page.

**Comment by csete** [comment]
https://github.com/csete/gqrx/releases/tag/v2.9
