### ISSUE TITLE
Remote control from outside

### ISSUE THREAD

**Issue by vk4tec** [csete/gqrx#564]
Can I please get clarification that gqrx can be controlled from outside the local pc. I would like to connect to gqrx using perl tcp socket and control frequency and mode for satellite tracking. Andrew

**Comment by alexf91** [comment]
You have to add the controlling host to the list of allowed hosts.
http://gqrx.dk/doc/remote-control

Please use the mailing list for support questions.

**Comment by csete** [comment]
Works fine for me.
