### ISSUE TITLE
undefined reference to `rtlsdr_set_bias_tee'

### ISSUE THREAD

**Issue by FFY00** [csete/gqrx#567]
Building in a ubuntu based distribution.
```
[100%] Linking CXX executable gqrx
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `rtlsdr_set_bias_tee'
```

I can't use the version from the repository because it doesn’t show the antennas in the dropdown for my LimeSDR.

**Comment by csete** [comment]
You know if it wasn't because I already answered this at least 10 times both here on github and on the mailing list, I might have given you the very simple and straightforward answer. But since I have, I hereby invite you to practice your search skills.
