### ISSUE TITLE
(HackRF) FATAL: setupStream invalid channel selection

### ISSUE THREAD

**Issue by daxorid** [csete/gqrx#569]
Attempting an initial run at using gqrx.

Stock GNU Radio works fine, and the output of hackrf_info looks fine:

> 
> hackrf_info version: unknown
> libhackrf version: unknown (0.5)
> Found HackRF
> Index: 0
> Serial number: 0000000000000000a06063c8254b2f5f
> Board ID Number: 2 (HackRF One)
> Firmware Version: 2017.02.1 (API:1.02)
> Part ID Number: 0xa000cb3c 0x00674f63

But when attempting to launch gqrx, I get "FATAL: setupStream invalid channel selection":

> linux; GNU C++ version 7.2.0; Boost_106200; UHD_003.010.002.000-0-unknown
> gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.11
> built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy soapy redpitaya 
> FM demod gain: 3.05577
> Resampling audio 96000 -> 48000
> IQ DCR alpha: 1.04166e-05
> Using audio backend: auto
> BookmarksFile is /home/dax/.config/gqrx/bookmarks.csv
> Cannot connect to server socket err = No such file or directory
> Cannot connect to server request channel
> jack server is not running or cannot be started
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
> JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for 4294967295, skipping unlock
> 
> RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.
> 
> gr-osmosdr 0.1.4 (0.1.4) gnuradio 3.7.11
> built-in source types: file osmosdr fcd rtl rtl_tcp uhd miri hackrf bladerf rfspace airspy soapy redpitaya 
> [INFO] Opening HackRF One #0 a06063c8254b2f5f...
> 
> FATAL: setupStream invalid channel selection
> 
> Trying to fill up 1 missing channel(s) with null source(s).
> This is being done to prevent the application from crashing
> due to gnuradio bug #528.

**Comment by csete** [comment]
You should fix this first:
> RtApiAlsa::getDeviceInfo: snd_pcm_open error for device (hw:0,0), Device or resource busy.

Note that this is a bug tracker, not a support forum. Please see http://gqrx.dk/user-support
(also be sure to check the list of known problems, in particular the one concerning gnuradio 3.7.11, before reporting problems)
