### ISSUE TITLE
Record above dBFS

### ISSUE THREAD

**Issue by vk4tec** [csete/gqrx#575]
Hello

I often record Falconsat-3 this is a manual process

Can we kick off a triggered recording based on signal strength with a hysteris loop of say 30 seconds

A level would be set to start recording 

A

**Comment by LongnoseRob** [comment]
This may notbe excatly what you want, but GQRX can be remotely controlled
to start/stop audio recording from gpredict.

**Comment by vk4tec** [comment]
Thank you 

Looking

**Comment by csete** [comment]
Please also check the list of existing issues before posting.
Closing as duplicate of issue #109.
