### ISSUE TITLE
Everything works expect the spectrum

### ISSUE THREAD

**Issue by mehdideveloper** [csete/gqrx#579]
Hi
I've compiled the latest Gqrx from git and it does not have a spectrum (although it has waterfall)
It was working before this, but this happened after I fetched and compiled the latest version.

Info:
Mac OS X 10.13.2
Gqrx v2.9-4-g4138038
gr-osmosdr v0.1.4-98-gc653754d (0.1.5git)

Here's a screenshot:

<img width="1392" alt="screen shot 2017-12-20 at 11 34 25 am" src="https://user-images.githubusercontent.com/12119776/34203180-7712029e-e57a-11e7-8182-77b009210bfe.png">

Any ideas?
Thanks

**Comment by alexf91** [comment]
Start with `gqrx -r`.
The problem occurs sometimes after updates. The `-r` flag resets the 
configuration file and should fix the problem.

**Comment by mehdideveloper** [comment]
Oh thank you very much.
