### ISSUE TITLE
AGC disable, restore to slider state

### ISSUE THREAD

**Issue by willcode** [csete/gqrx#587]
Feature request.

When AGC is disabled, restoreManualGains() uses saved settings instead of the current manual gain settings shown on-screen. Can the current slider state be used instead?

Also, all gains appear to be temporarily set to 0 right before the saved settings are applied, causing a flurry of set_gain() calls.

**Comment by csete** [comment]
I agree it would be better to use the current slider state. I will take a look if I come back to work on gqrx again.

**Comment by csete** [comment]
Hi @willcode 

Manual gain settings are now restored from the sliders instead of the settings file. Let me know if it doesn't work as expected.
