### ISSUE TITLE
4.3"TFT screen

### ISSUE THREAD

**Issue by gopanxto** [csete/gqrx#592]
Do there any option to run GQRX on rpi3 with 4.3" tft with resolution of 480x272?  Now the application gqrx size exceeds the screen limits . I need to use this as a panadaptor with rtl sdr dongle modified to receive HF.

**Comment by csete** [comment]
This is a bug tracker, not a tech support forum. Please see http://gqrx.dk/user-support and make sure you search the archives because this topic has been discussed many times.
