### ISSUE TITLE
Problem on Windows10 -- missing RTL2823 from devices list

### ISSUE THREAD

**Issue by szg0000** [csete/gqrx#596]
Under Windows10 the RTL2838 DVBT dongle is not shown, but plugged in.

![gqrx_rtl2838missing](https://user-images.githubusercontent.com/18247040/36246704-4ac707f0-1231-11e8-8b5f-71c49ffa0f84.png)

**Comment by csete** [comment]
This is not a bug in gqrx but a problem with packaging and/or installation. I haven't made the package and I have no clue about windows, so you will have to ask somewhere else.
