### ISSUE TITLE
ABI compatibility mismatch

### ISSUE THREAD

**Issue by kasmf** [csete/gqrx#597]
how to solve the error bellow ? if you have any idea post the solution with clear steps, in order to combat-able by upgrade or downgrade the UHD library or other solution.
RuntimeError: 
GR-UHD detected ABI compatibility mismatch with UHD library.
GR-UHD was build against ABI: 3.9.0-0,
but UHD library reports ABI: 3.10.3
Suggestion: install an ABI compatible version of UHD,
or rebuild GR-UHD component against this ABI version.

**Comment by csete** [comment]
Not a bug in gqrx.

**Comment by liumaolin-931** [comment]
I am a novice and I have the same problem，but I don't want to reload UHD,how to solve it？thanks
