### ISSUE TITLE
ABI-combaatibility error

### ISSUE THREAD

**Issue by kasmf** [csete/gqrx#599]
how to solve the error bellow ? if you have any idea post the solution with clear steps, in order to combat-able by upgrade or downgrade the UHD library or other solution.
RuntimeError: 
GR-UHD detected ABI compatibility mismatch with UHD library.
GR-UHD was build against ABI: 3.9.0-0,
but UHD library reports ABI: 3.10.3
Suggestion: install an ABI compatible version of UHD,
or rebuild GR-UHD component against this ABI version.

**Comment by csete** [comment]
I already told you in issue #597 that this is not a gqrx bug. This is a gqrx bug tracker, not a helpdesk.
Please stop spamming or else I will block you from the project.

Pro tip: Use google.
