### ISSUE TITLE
gnuradio

### ISSUE THREAD

**Issue by kasmf** [csete/gqrx#601]
how to uninstall gnuradio installed from source (hint installed from: https://kb.ettus.com/Building_and_Installing_the_USRP_Open-Source_Toolchain_(UHD_and_GNU_Radio)_on_Linux) in order to install new version ?

**Comment by csete** [comment]
Why can't people understand that this is a gqrx bug tracker and not a freaking help desk...

**Comment by alexf91** [comment]
It seems to get worse. Maybe an issue template with a link to the mailing list would help.
https://blog.github.com/2016-02-17-issue-and-pull-request-templates/

**Comment by csete** [comment]
I thought of that, but it I doubt I am able to explain this even in a template to people who think this is the place to post gnuradio questions. We'll see, for now I can just close issues.

**Comment by cbryant1000** [comment]
Maybe block repeated offenders?

Cliff Bryant                  __

___________________/_O_______________________________

 email: cbryant1000@gmail.com | cell: (617) 417-1414 | KB1YQL
