### ISSUE TITLE
Gqrx requires QT4 os QT5?

### ISSUE THREAD

**Issue by szg0000** [csete/gqrx#602]
I tried to compile GQRX with qt5-qmake first, but it requires qt4-qmake:

```
user@debian:~/gqrx.git/build$ qmake ..
qmake: could not exec '/usr/lib/x86_64-linux-gnu/qt4/bin/qmake': No such file or directory
```

----------After install qt4-qmake----------

```
user@debian:~/gqrx.git/build$ qmake ..
Project ERROR: Gqrx requires Qt 5.

```

**Comment by alexf91** [comment]
Your default Qt points to Qt4. Try `qmake-qt5 ..`

This is a bugtracker. Support is at https://groups.google.com/forum/#!forum/gqrx

**Comment by szg0000** [comment]
Thanks.

`/usr/lib/x86_64-linux-gnu/qt5/bin/qmake ..` helps.
