### ISSUE TITLE
Color selector button in tag list has become too large

### ISSUE THREAD

**Issue by csete** [csete/gqrx#622]
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gqrx/l8qfsJzub_E/iPZ0oimHBAAJ

---

It looks like the width of the color selector button has increased gradually from Qt 5.6 -> 5.9 -> 5.10.

**Comment by kukabu** [comment]
The similar behavior in the "Add bookmark" window.

**Comment by kolbma** [comment]
Is this still a problem? I can't reproduce it... looks always good here.

**Comment by argilo** [comment]
It appears this was fixed in 2ec4f0826e9e82340e0c3a00e277c526da65c13d.
