### ISSUE TITLE
Add [space] keybinding

### ISSUE THREAD

**Issue by Arinerron** [csete/gqrx#629]
Hello,

It'd be neat if the space bar was a keybinding to toggle DSP processing (like Ctrl+D). It's a simple change and in my opinion, it would make gqrx easier to use.

I'll make a PR if you'd like, but I am not sure I know exactly how to add it (I'm not a C++ dev).
**Edit:** After looking in the source code, it appears as though `on_actionDSP_triggered(true/false)` should be called to toggle DSP processing, but I don't know how to do key events. Sorry.

Thanks,
    Aaron E. (aka: Arinerron)

**Comment by LongnoseRob** [comment]
CTRL-D is the current shortcut

(Sent from my mobile device)

**Comment by Arinerron** [comment]
Yup, I updated the issue on GitHub. :)


Sincerely,
    Aaron E. (aka: arinerron <https://www.arinerron.com/>)

**Comment by csete** [comment]
Space bar is used by most graphical operating systems to activate the currently selected widget, which is an important part of making GUI applications usable for e.g. blind people. Sorry, but I prefer to stay with the existing short cut.
