### ISSUE TITLE
SoapyRemote crashes

### ISSUE THREAD

**Issue by ast** [csete/gqrx#632]
I have written two SoapySDR drivers to use my radios with GQRX. I've noticed that GQRX crashes if the SoapyRemote server crashes (or is terminated). I'm not sure if this is an issue with GQRX or gr-osmosdr but it's not expected behaviour. I will look into it but posting this issue also if anyone has any ideas?

Latest versions of GQRX, gr-osmosdr and SoapySDR.

```
[ERROR] SoapySSDPEndpoint::sendTo(udp://[ff02::c]:1900) = -1
  sendto(udp://[ff02::c]:1900) [99: Cannot assign requested address]
[ERROR] SoapyLogAcceptor::handlerLoop(tcp://sdr.local:1234) FAIL:
SoapyRPCUnpacker::recv(header) FAIL:
terminate called after throwing an instance of 'std::runtime_error'
  what():  SoapyRPCUnpacker::recv(header) FAIL:
[1]    3660 abort (core dumped)  ./gqrx
```

**Comment by csete** [comment]
Nothing to fix in gqrx. For discussions and tech support please use the mailing list, http://gqrx.dk/user-support
