### ISSUE TITLE
Software-based Equalizer?

### ISSUE THREAD

**Issue by Arinerron** [csete/gqrx#636]
Hey,

How difficult would it be to add a simple software-based equalizer to gqrx? When listening to FM radio on gqrx, the higher-pitched audio tends to play louder than the lower-pitched audio, and it would be useful to be able to adjust for it in gqrx.

I'd add it myself, but I don't know C++ well enough :/

Thanks,
    Aaron E.

**Comment by csete** [comment]
Not difficult, but everything requires time to do and I don't anticipate any further development of gqrx since I work on a new SDR project now.

**Comment by Arinerron** [comment]
Ah cool, what are you up to now @csete (if you don't mind me asking)?

gqrx is pretty cool software. I keep finding reasons to learn C++. If development does end up stopping, I'm going to learn what I can to be able to contribute to gqrx. :)

Anyway, thanks for the reply.

**Comment by csete** [comment]
> Ah cool, what are you up to now @csete (if you don't mind me asking)?

Just some light-weight SDR that doesn't have all the dependencies like gqrx. Preview will be available for testing very soon.

**Comment by argilo** [comment]
> When listening to FM radio on gqrx, the higher-pitched audio tends to play louder than the lower-pitched audio

I suspect this was due to de-emphasis being broken. That was fixed in #733 and #784.

I don't see much reason to add an equalizer into gqrx, so I'll close this off for now.
