### ISSUE TITLE
direct_samp=1 causes crash

### ISSUE THREAD

**Issue by pyeager** [csete/gqrx#64]
Device is a Terratec T Stick + (0ccd:00d7)
Sample output:

linux; GNU C++ version 4.7.2; Boost_104900; UHD_003.005.001-34-g11a21387

gr-osmosdr (ede9c804 / 0.0.1git) supported device types:
    file fcd rtl rtl_tcp uhd 
>>> gr_fir_ccf: using SSE
>>> gr_fir_ccc: using SSE
Using Volk machine: sse2_32_mmx_orc
>>> gr_fir_fff: using SSE
gr-osmosdr (ede9c804 / 0.0.1git) supported device types:
    file fcd rtl rtl_tcp uhd 
Using device #0 Realtek RTL2838UHIDIR SN: 00000001
Found Elonics E4000 tuner
Exact sample rate is: 1500000.014901 Hz

Using device #0 Realtek RTL2838UHIDIR SN: 00000001
cb transfer status: 5, canceling...
Detached kernel driver
Found Elonics E4000 tuner
Qt has caught an exception thrown from an event handler. Throwing
exceptions from an event handler is not supported in Qt. You must
reimplement QApplication::notify() and catch all exceptions there.

terminate called after throwing an instance of 'std::runtime_error'
  what():  In hierarchical block osmosdr_source_c_impl, output 1 is not connected internally
Aborted (core dumped)

**Comment by csete** [comment]
direct_samp=1 or 2 seems to work fine.
