### ISSUE TITLE
Remove the IQ DC spike in the central frequency

### ISSUE THREAD

**Issue by jimmystelzer** [csete/gqrx#641]
There is a ghostop14 project in github that claim to resolve this issue by creating an GNURadio block that pre filter the IQ, consider add this functionality to the Gqrx. Here is the github page https://github.com/ghostop14/gr-correctiq.

**Comment by csete** [comment]
What issue do you want resolved? We already have both DC removal and I/Q balancing, both automatic. If there is something else that works better, feel free to test it and demonstrate it; however, as I have explained many times in the past, I don't anticipate any further development of gqrx.
