### ISSUE TITLE
'Device' spontaneously switches to 'Other'

### ISSUE THREAD

**Issue by yurivict** [csete/gqrx#642]
In the version 2.11.5, on the 'Configure I/O devices' I choose 'Spyserver client' as'Device' with 'Device string': ```host=airspy.com,port=5555,spyserver=0``` and click "Ok". When I come back to this screen, 'Device' is 'Other'.

So I can never change to 'Spyserver client'.

**Comment by alexf91** [comment]
This is not a problem. The only thing that counts is the device string. The "Device" field only exists to make it easier to select detected devices.

**Comment by yurivict** [comment]
But this is a very unnatural and confusing behavior.

**Comment by csete** [comment]
This happens when the device string is changed from the default one.
