### ISSUE TITLE
Waterfall doesn't move when the frequency at the top is changed

### ISSUE THREAD

**Issue by yurivict** [csete/gqrx#644]
I change the frequency. The numbers on the scale change but the spectrum itself doesn't move.
So if there was some radiostation, after the move it is obviously misplaced.
Same with the 'Frequency' spin control. It changes the numbers, but doesn't move the spectrum.

In the end, it isn't clear what frequency the radiostation is on.

2.11.5 on FreeBSD.

**Comment by csete** [comment]
Your SDR device is probably broken. Please use the mailing list for user support, thanks.
http://gqrx.dk/user-support

**Comment by yurivict** [comment]
I don't use a device. I use the new SpyServer support in https://github.com/racerxdl/gr-osmosdr

**Comment by csete** [comment]
That's experimental at best. I barely had 5 minutes to test it. Anyway, the server is probably locked to not allow changing the hardware frequency.

**Comment by yurivict** [comment]
Most likely that experimental project is still unstable, that's why, because all servers can't be locked.

**Comment by racerxdl** [comment]
That's weird. Here it works just fine (only if I lock the server, then it doesnt change).
![gqrx-opt](https://user-images.githubusercontent.com/578310/41825417-26422eca-77f6-11e8-94bf-58c394b3c8b9.gif)

Can you provide a server address that you find the issue?

**Comment by yurivict** [comment]
host=airspy.com,port=5557,spyserver=0

**Comment by yurivict** [comment]
Why does it show ip=127.0.0.1 for you? Do you use a proxy?
-----
With host=airspy.com,port=5557,spyserver=0

**Comment by yurivict** [comment]
![screenshot-2018-06-24_18 00 35](https://user-images.githubusercontent.com/271906/41825951-91f32ece-77da-11e8-820f-9bc10a30da63.gif)

**Comment by racerxdl** [comment]
This server only streams from 6.9MHz~ to 7.720MHz~ so anything outside range will be empty.
![gqrx-airspy com5557-optimized](https://user-images.githubusercontent.com/578310/41826049-fbccd1c0-77fc-11e8-9ffd-762a9ae91537.gif)

PS: My picture showed localhost because the server is on my machine.

**Comment by yurivict** [comment]
Its upper limit is 7.654MHz.
