### ISSUE TITLE
Wrong use of &&-Operator in parser_impl.cc

### ISSUE THREAD

**Issue by dk7ob** [csete/gqrx#647]
Building gqrx under Ubuntu 18.04 with gcc 7.3.0 returns the following warnings:

/home/wofritz/sdr/gqrx/src/dsp/rds/parser_impl.cc: In member function ‘void gr::rds::parser_impl::decode_optional_content(int, long unsigned int*)’:
/home/wofritz/sdr/gqrx/src/dsp/rds/parser_impl.cc:449:36: warning: ‘<<’ in boolean context, did you mean ‘<’ ? [-Wint-in-bool-context]
    label = (free_format[i] && (0xf << ff_pointer));
/home/wofritz/sdr/gqrx/src/dsp/rds/parser_impl.cc:452:66: warning: ‘<<’ in boolean context, did you mean ‘<’ ? [-Wint-in-bool-context]
    content = (free_format[i] && (int(pow(2, content_length) - 1) << ff_pointer));

From the context I think the logical && should actually be a bit wise &.

**Comment by csete** [comment]
We should take a look at whether the code has been updated upstream, if not fix it and submit a patch.
