### ISSUE TITLE
How to build with RPI 

### ISSUE THREAD

**Issue by bg1jt** [csete/gqrx#650]
Hello!
I use the software GQRX SDR you wrote on the raspberry pi. Thank you very much for providing such excellent software, and I also want to use the RPI GPIO to expand some buttons. I have no problem when I compile the software, but when you run it, prompt Error in `./gqrx': corrupted double-linked list: 0x0249c338, I don't know How do I have the right configuration,

THK~

**Comment by csete** [comment]
Technical support is provided through a mailing list, please see http://gqrx.dk/user-support
