### ISSUE TITLE
gqrx not compatible with current Soapy API 0.7

### ISSUE THREAD

**Issue by MStrecke** [csete/gqrx#653]
Doing a fresh install - this time Ubuntu 18.04 LTS - is always a source of hours of fun ... getting your stuff working again :-)

As I speculated [here](https://groups.google.com/forum/#!topic/gqrx/kzwTpELml_0) the current version of gqrx - as available via the Ubuntu ppa repositories - is not compatible with the current soapy API which is needed to access the SDRplay RSP2.

The device string "soapy=0,driver=sdrplay" results in:

`      FATAL : SoapySDR::Device::make()  no match.`

At sdrplay.com you currently get Linux x86 API/HW driver V2.13.

As I don't know of any binary source for the sdrdriver I'm compiling it from source as described [here](https://github.com/pothosware/SoapySDR/wiki/BuildGuide#ubuntu).

SoapySDRUtil reports: 

```
Lib Version: v0.7.0-g37429d89
API Version: v0.7.0
ABI Version: v0.7
```

But I know that it worked end of last year....

Another clean install later, I'm using Linux x86 API/HW driver V2.11 that was still in my Download folder.

From the SoapySDR's git I'm checking out:
`  git checkout soapy-sdr-0.6.1`

From SoapySDRPlay's git I'm using:
`  git checkout ca7e028cd834480976d7bc002f7f4a1e5c2b3b1c`
  
Then I cook it all according to recipe - let the compiler stir it for five minutes and voilà... `SoapySDRUtil --info` now shows:

```
Lib Version: v0.6.1-g4daa4329
API Version: v0.6.0
ABI Version: v0.6
```

gqrx finds the hardware and lets the water fall again.

Ok. This is the work-around. What is the fix?

In commit https://github.com/pothosware/SoapySDR#2db018ef328f03368efc7e145bdf9c8b444ebc34 the log entry reads:

> Author: Josh Blum <josh@joshknows.com>
> Date:   Fri Jan 12 15:40:07 2018 -0600
> 
>     set soapysdr abi version to 0.7 for recent additions
>     
>     Although the core device ABI has not changed on the development branch,
>     modules may use the new converter API or verion registration API.
>     This creates a compatibility mismatch for modules built on the
>     development branch vs the previous release. Therefore, modules built
>     against this branch will be installed in the new modules directory for 0.7.
>

**Comment by csete** [comment]
Gqrx does not know anything about SoapySDR and there is nothing to fix in gqrx. When somebody packages SoapySDR 0.7 for the Ubuntu PPA it will be available. You can not arbitrarily mix binary and source builds. This and a lot of other useful info about SDRPlay support, e.g. how to get it working without SoapySDR, is already available in the mailing list archives. Please keep the discussion there.
