### ISSUE TITLE
Can an Auto Squelch command please be added to Remote Control Settings

### ISSUE THREAD

**Issue by prynhart** [csete/gqrx#655]
When using Gqrx for a long period of time, the atmospheric conditions can change - and I'd really like a way to automate the pressing of the "A" (Auto Squelch) button.  If this feature could be added to the remote control then this would be a programmatic way to do so.  With Thanks in Advance, Patrick

**Comment by alexf91** [comment]
I don't think we need a special command for this.
You can do this by reading the current signal level with "l STRENGTH" and then setting the squelch threshold with "L SQL <value>".

**Comment by prynhart** [comment]
Good point - thank you Sir :)
