### ISSUE TITLE
gqrx and pulseaudio

### ISSUE THREAD

**Issue by lu7did** [csete/gqrx#665]
Hello, I'm trying to use grqx with pulseaudio on a Raspberry Pi Mod 3 in order to use other programs such as FLDIGI or WSJTX. Have both installed and working properly. gqrx works very good as long as the output is the USB sound card speaker. In the other hand pulseaudio works ok when used with another setup using a combination of rtl-sdr drivers, csdr and ncat with mplayer. When opening pavucontrol gqrx isn't listed as a playback device (virtual0 and virtual1 lines are). gqrx version is 2.11.5. Any recommendations? Thanks in advance, Pedro, LU7DID

**Comment by csete** [comment]
You need to provide more details about how gqrx was installed, which device you select etc. But please don't use this bug tracker to tech support, please see http://gqrx.dk/user-support , thanks.
