### ISSUE TITLE
multiple waterfalls per device

### ISSUE THREAD

**Issue by drom** [csete/gqrx#672]
When working in HAM radio contests it is possible to capture all band by a single dongle but it is convenient to see multiple waterfalls, one per sub-band.

For example 144MHz band (1.5MHz) as 3 waterfalls:
  * 144.040 - 144.150 = 110KHz
  * 144.280 - 144.350 = 70KHz
  * 145.450 - 145.550 = 100KHz

Is this possible in GQRX?

**Comment by eu2aa** [comment]
it's impossible

**Comment by drom** [comment]
@csete how difficult would be to implement such feature?

**Comment by csete** [comment]
@drom I no longer work on gqrx as it has become unfeasible to maintain it. It's just broken at the architectural level and the only way to fix it IMO is to rewrite most of it from scratch, which is ongoing.

**Comment by drom** [comment]
Thank you for your reply @csete

**Comment by csete** [comment]
I can tell you that doing a quick hack with two or more spectrum displays could  be done relatively easily, as long as you don't want multiple receivers/demodulators running in parallel.

**Comment by alexf91** [comment]
I have just implemented this hack:
https://github.com/alexf91/gqrx/tree/multiple-waterfalls
![multiple-waterfalls](https://user-images.githubusercontent.com/2362689/51078972-18abfd00-16bf-11e9-93bd-6310e5c0b85a.png)
