### ISSUE TITLE
how to calculate decimation fir filter coefficient taps in dsp/filter/fir_decim_coef.h?

### ISSUE THREAD

**Issue by quanpm4900** [csete/gqrx#674]
Could anybody tell me how to calculate decimation fir filter coefficient taps in dsp/filter/fir_decim_coef.h?
I don't understand what is follow mean:
// Stage   Passband        Stopband        Decimation
// FIR1    0.4500000000    0.5500000000    2
How to use gnuradio to design taps with parametes as above?
Please help me, thank in advanced!

**Comment by csete** [comment]
This is a bug/feature tracker. For technical support please see http://gqrx.dk/user-support
