### ISSUE TITLE
Hardware AGC has to be reset when starting GQRX

### ISSUE THREAD

**Issue by qualitymanifest** [csete/gqrx#676]
- Operating system: Linux Mint 19
- GQRX version: 2.9
- Installed from: Synaptic Package Manager
- Device: RTL-SDR v3 dongle

Every time I start GQRX I have to un-check and re-check "Hardware AGC". I get no reception until I do and the waterfall display looks completely different afterwards, as shown in the screenshot provided. It works totally fine after I reset it.

I found this related issue https://github.com/csete/gqrx/issues/370 that says it was fixed, but my GQRX version was released long after that issue was said to have been resolved.

Thanks in advance, I really appreciate this software!

![hardware_agc](https://user-images.githubusercontent.com/13897419/52075413-351eb500-255a-11e9-8968-25ba6248e296.png)

**Comment by csete** [comment]
Please try 2.11! We have an Ubuntu PPA, a generic tar.gz binary, and an AppImage on the website, the latter two will not even require uninstalling 2.9 see http://gqrx.dk/download

**Comment by csete** [comment]
Works for me with gqrx 2.11 and Qt 5.6
