### ISSUE TITLE
thread[thread-per-block[0]: <block spyserver_source_c (48)>]: boost::condition_variable::wait failed in pthread_cond_wait: Invalid argument

### ISSUE THREAD

**Issue by PA8E** [csete/gqrx#681]
Running Gqrx software defined radio receiver v2.11.5-9-g48ba997 with gr-osmosdr v0.1.4-144-g47a39bad (0.1.5git) gnuradio 3.7.11
built-in source types: file fcd rtl_tcp rfspace airspy redpitaya spyserver on Linux HP-ZBook 4.15.0-46-generic #49-Ubuntu SMP Wed Feb 6 09:33:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux. 
When connecting to a spyserver it gives me about 2 seconds of audio and then it silence with error:

thread[thread-per-block[0]: <block spyserver_source_c (48)>]: boost::condition_variable::wait failed in pthread_cond_wait: Invalid argument

Tried different sample rates etc. Keep getting the same error.

**Comment by csete** [comment]
Hi @PA8E 

spyserver_source_c comes from an external repository and is not part of gqrx. I can't fix anything in gqrx, sorry.
