### ISSUE TITLE
Recording save location and permissions

### ISSUE THREAD

**Issue by nardhini** [csete/gqrx#685]
I am using gqrx v2.11.5 and the first time I tried to record an audio file, it didn't have a default location set (the location field was blank) and hence it tired to record the file to the root(/) folder. Since it didn't have permission to write to the root folder, it failed but no error message was displayed. gqrx should have home folder as the default location and throw an error message when permission is not adequate.

**Comment by csete** [comment]
Gqrx does use the home directory of the user running the application as default:
https://github.com/csete/gqrx/blob/master/src/qtgui/dockaudio.cpp#L377

**Comment by nardhini** [comment]
Yes, my bad, the home folder is the default location. But, gqrx doesn't show an error message when the selected folder doesn't have write permission. For example, when I set the location to /root and recorded an audio, it displayed "Recording audio to /root/gqrx*.wav" but the file was not saved at that location.

**Comment by csete** [comment]
I agree that there are many behavioral problems with gqrx. Unfortunately, most of these errors occur in external libraries (gnuradio, gr-osmosdr) and it has proven extremely difficult to make proper error reports due to the way these errors are reported. I welcome patches that fix such things.
