### ISSUE TITLE
Add support for signal hound SDR

### ISSUE THREAD

**Issue by tu21shar** [csete/gqrx#691]
I am trying to use source block from gr-bb60 module in gqrx.
But it gives me this undefined reference error on make.

I assume this pertains to linking of the gr-bb60 module code. So I have tried
adding the gr-bb60 module to the find_package in Cmakelists of gqrx and created a .pc for it to be found by pkg config module. But still the error remains.

#include <bb60c/source.h>  //header for my gr-bb60 module

gr::bb60c::source::sptr     src1;  //the pointer declared in the .h
file of receiver.h in gqrx. It gives no error

src1=gr::bb60c::source::make(1e9, -20, -1, -1, 2, 18e6, false, false,
0, 0); //the make for the block in receiver.cc file of GQRX which gives
this error

find_package(Gnuradio-bb60c REQUIRED) // find package in the Cmake lists
/***Contents of .pc file created*****/
INCLUDE(FindPkgConfig)
PKG_CHECK_MODULES(PC_BB60C bb60c)

FIND_PATH(
    BB60C_INCLUDE_DIRS
    NAMES bb60c/api.h
    HINTS $ENV{BB60C_DIR}/include
        ${PC_BB60C_INCLUDEDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/include
          /usr/local/include
          /usr/include)

FIND_LIBRARY(
    BB60C_LIBRARIES
    NAMES gnuradio-bb60c
    HINTS $ENV{BB60C_DIR}/lib
        ${PC_BB60C_LIBDIR}
    PATHS ${CMAKE_INSTALL_PREFIX}/lib
          ${CMAKE_INSTALL_PREFIX}/lib64
          /usr/local/lib
          /usr/local/lib64
          /usr/lib
          /usr/lib64)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(BB60C DEFAULT_MSG BB60C_LIBRARIES
BB60C_INCLUDE_DIRS)
MARK_AS_ADVANCED(BB60C_LIBRARIES
BB60C_INCLUDE_DIRS)
/************************************/

**Comment by csete** [comment]
Sorry, but I don't see how this is a bug in gqrx. If you want to add support for new hardware you should do it in gr-osmosdr and not directly in gqrx.
