### ISSUE TITLE
Raspberry 4 and Raspbian Buster

### ISSUE THREAD

**Issue by sailoog** [csete/gqrx#693]
Trying to test gqrx in the new Raspberry 4 I am getting this error running gqrx-sdr-2.11.5-linux-rpi3:

`error while loading shared libraries: libboost_program_options.so.1.62.0: cannot open shared object file: No such file or directory`

To run the RPi4 you need the latest Raspbian based on Debian Buster. The version of libboost_program_options is higher:

`libboost-program-options-dev is already the newest version (1.67.0.1+b1).`

Do you have plans to create a version for RPi4?

**Comment by csete** [comment]
No plans at the moment.

**Comment by csete** [comment]
Also, note that Debian Buster already has version 2.11.5 so that should work. If it doesn't report bugs to Debian. It is still in testing so they might have a chance to fix the packages before it becomes stable.

**Comment by Hosam-M** [comment]
i have same problem with Pi3B+ and i am using last Version:June 2019 Release date:2019-06-20 Kernel version:4.19 all try show
 error while loading shared libraries: libboost_program_options.so.1.62.0: cannot open shared object file: No such file or directory
or 
No such file or directory 
i dont know if this problem come from 32bit/64bit and bus things as some guys in the web say with another software or not 
so if someone can help we will be thankful

**Comment by csete** [comment]
Dear friends,

As the [website](http://gqrx.dk/download/gqrx-sdr-for-the-raspberry-pi) says:

>Gqrx SDR is available as binary package for the Raspberry Pi 3 running Raspbian Stretch and other ARM v6 running a **Debian Stretch** based OS.

And we now know that this binary will not work on **Debian Buster**. However, we also know that the same version is already available in Debian Buster, so please try and use that for now.

**Comment by Hosam-M** [comment]
dear i am really thankful for your kinds and patience answering our questions i wish you all the best
