### ISSUE TITLE
Gqrx disable bias tee with RTL-SDR V3

### ISSUE THREAD

**Issue by alex27riva** [csete/gqrx#695]
Hi everyone, I'm using Manjaro Linux on my PC, I use this command to enable bias tee on my RTL-SDR V3 `./rtl_biast -b 1` and it works.
But when open Gqrx software, it disables bias tee on my dongle, how can I fix this?

**Comment by csete** [comment]
Please use the mailing list for technical support: http://gqrx.dk/user-support
There are already threads about enabling bias tee in gqrx.
