### ISSUE TITLE
*New user* Can't seem to get gqrx to run on rpi4

### ISSUE THREAD

**Issue by RogueBanana** [csete/gqrx#699]
Greetings folks,

BLUF: I followed the guide to install the RTL-SDR and gqrx, but when i get to the end to execute the gqrx file I can't get it to do anything.

Bare with me here, i'm pretty new to this whole Pi world and linux.

I followed the readme file for the latest release "gqrx-sdr-2.11.5-linux-rpi3". Is there a difference for rpi4? 

Everything went fine until i got to the part where it wants me to enable access to USB devices. the readme says "Open a terminal and change to the gqrx director then type: sudo cp udev/*.rules /etc/udev/rules.d/ "

When i typed "cd gqrx" i got the no such file or directory error. So i did "mkdir gqrx" then "cd gqrx" and entered the above command which returned "/udev/*.rules" no such file or directory

So i thought "Maybe it meant the folder where I had all of the gqrx files installed?" So i typed in: "cd /home/pi/Downloads/gqrx-sdr-2.11.5-linux-rpi3" which put me in that directory. Then i typed in the above command and it took. I tried clicking the gqrx executable, it prompted me to select execute or execute in terminal...and nada. Nothing. No windows opened.

What am i missing here folks? please help a newbie out!

**Comment by csete** [comment]
Hello,

The Raspberry pi binaries available from us were built for the previous version of Raspbian OS (Stretch) and do not work with the latest version of the OS (Buster). However, the latest version of gqrx should already be available in Raspbian itself.

Please note that we this site for development and not for user support. To get help please use out mailing list: http://gqrx.dk/user-support
There are already many threads about this issue.
