### ISSUE TITLE
python error

### ISSUE THREAD

**Issue by vampire2310** [csete/gqrx#702]
PyBOMBS.install_manager - INFO - Installing package: qwt6
PyBOMBS.Packager.apt - INFO - Install python-apt to speed up apt processing.
Building: (100%) [=========================================================]
cd src/ && ( test -e Makefile || /usr/lib/qt5/bin/qmake -o Makefile /usr/local/src/qwt6/src/src.pro ) && make -f Makefile
make[1]: Entering directory '/usr/local/src/qwt6/src'
compiling qwt_abstract_scale_draw.cpp
In file included from ../../../../include/x86_64-linux-gnu/qt5/QtCore/qlocale.h:43,
from ../../../../include/x86_64-linux-gnu/qt5/QtCore/qtextstream.h:46,
from ../../../../include/x86_64-linux-gnu/qt5/QtCore/qdebug.h:49,
from qwt_interval.h:17,
from qwt_scale_div.h:14,
from qwt_abstract_scale_draw.h:14,
from qwt_abstract_scale_draw.cpp:10:
../../../../include/x86_64-linux-gnu/qt5/QtCore/qvariant.h: In constructor ‘QVariant::QVariant(QVariant&&)’:
../../../../include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:273:25: warning: implicitly-declared ‘constexpr QVariant::Private& QVariant::Private::operator=(const QVariant::Private&)’ is deprecated [-Wdeprecated-copy]
273 | { other.d = Private(); }
| ^
../../../../include/x86_64-linux-gnu/qt5/QtCore/qvariant.h:399:16: note: because ‘QVariant::Private’ has user-provided ‘QVariant::Private::Private(const QVariant::Private&)’
399 | inline Private(const Private &other) Q_DECL_NOTHROW
| ^~~~~~~
In file included from qwt_scale_map.h:14,
from qwt_abstract_scale_draw.cpp:14:
qwt_transform.h: At global scope:
qwt_transform.h:110:5: error: ‘QT_STATIC_CONST’ does not name a type
110 | QT_STATIC_CONST double LogMin;
| ^~~~~~~~~~~~~~~
qwt_transform.h:111:5: error: ‘QT_STATIC_CONST’ does not name a type
111 | QT_STATIC_CONST double LogMax;
| ^~~~~~~~~~~~~~~
make[1]: *** [Makefile:3819: obj/qwt_abstract_scale_draw.o] Error 1
make[1]: Leaving directory '/usr/local/src/qwt6/src'
make: *** [Makefile:48: sub-src-make_first-ordered] Error 2
PyBOMBS.Packager.source - ERROR - Build failed. See output above for error messages.
PyBOMBS.Packager.source - ERROR - Problem occurred while building package qwt6:
Build failed.
PyBOMBS.install_manager - ERROR - Error installing package qwt6. Aborting.

**Comment by csete** [comment]
This has nothing to do with gqrx
