### ISSUE TITLE
Pulseaudio issues 

### ISSUE THREAD

**Issue by link500** [csete/gqrx#706]
Ok, so I’m running into an issue trying to get gqrx running properly. I asked on the pi forums first but they couldn’t find a solution for me so I’ll try here next. I’ll copy/paste the description I gave there.

“I’ve been running into an error with my new raspberry pi 4.

I’m trying to use gqrx, I installed it via the add/remove software option since attempting too directly from the website the old way always gave me far more errors than this one ever since buster released.

So i get it installed, and it seemed like it worked at first...problem was there was no audio, I tried to switch to the analog function since I’m trying to run it through a Bluetooth speaker via its auxiliary/headphone jack, problem with that is as soon as i check the analog option it gets stuck at 2% volume, and soon as i try to raise the volume it immediately disables the analog AND hdmi options so neither is checked.

After this I just straight up reinstalled raspbian to see if maybe something some how got corrupted in the install(has happened before and figured no big deal since I didn’t have anything else on the pi) soon as I did this I’d get the pulseaudio error mentioned in the title and gqrx won’t start at all.

I then attempted something I read online about the error about completely uninstalling and reinstalling pulseaudio through terminal, and after doing that it went right back to the other issue where the analog and hdmi would get stuck at 2% volume and any attempts at increasing it would disable them.

When the issue with the volume being stuck on 2% happens, gqrx “technically” runs, as in its picking up signals can change frequencies etc, and I’m sure if i just recorded and saved a session and played it back as a file it’d probably work (haven’t tested this yet of course), but when I get the pulseaudio error it just stops the program from even starting.”

I’ve already attempted both recommendations from two posters there, neither recommendation helped, one had me install Pavucontrol, but it still wouldn’t let me increase the volume on either the 3.5mm jack or hdmi, disabling them once again as soon as I attempted to increase it. The other had me do a fresh install of pulseaudio and then attempt puIseaudio -D which didn’t do anything. also attempted to install gqrx the “old way” by navigating directly to the website, downloading the files, going through the readme text and copying udev rules to the gqrx folder etc., that brings its own slew of issues however since it was setup for rasbian stretch or older and not buster, it just completely terminates itself soon as it’s started.

Also forgive me for the dumb question since I’m still new to the pi and linux systems, but is there a way to install gqrx without pulseaudio attached to it? Since the analog/hdmi volume works fine when gqrx and pulseaudio aren’t installed.

**Comment by csete** [comment]
Hi,

Sorry for the late reply, but I only use this site for development as user support is provided through a mailing list, see http://gqrx.dk/user-support. I suggest you take a look at the archives since some people have reported having gqrx working on the Raspberry PI 4.

Gqrx can be compiled to use portaudio (ALSA) instead of pulseaudio and this is how our Rasberry Pi binaries are built. Unfortunately, I do not have time to update the Raspberry Pi binary to work with Rasbian Buster at the moment.
