### ISSUE TITLE
Set Bandwidth remotely

### ISSUE THREAD

**Issue by wx273** [csete/gqrx#713]
Hi Alexandru,
I need to set bandwidth 38KHz for some freqs and 110KHz for others. Is it possible now via remote or is it a FR please ?
So, F 137900000 38000000  or something similar ?
Thanks

**Comment by alexf91** [comment]
You can do this with the "M" command: `M WFM 38000`

**Comment by wx273** [comment]
Perfect !
Thanks very much :)
