### ISSUE TITLE
How to calculate the gain of the received signal

### ISSUE THREAD

**Issue by YFDY** [csete/gqrx#716]
I have received a GPS signal with my hackrf one,but I don't know how to calculate the power of the real signal without any gain. Should I calculate the power by subtracting the RF gain、the IF gain and the BB gain?
![003](https://user-images.githubusercontent.com/37526949/71230218-ba05ef00-2323-11ea-848b-4ef560a9f9cf.png)

**Comment by csete** [comment]
I don't know either, sorry. I suggest you try a tech forum (this is a bug tracker used for development).
