### ISSUE TITLE
Problems on macOS 10.15

### ISSUE THREAD

**Issue by cxy5014** [csete/gqrx#717]
Since macOS 10.15 banned the 32bit application, Gqrx could not work.
Could you please build the application for macOS 10.15 using 64bit?

**Comment by csete** [comment]
Sorry, but I do not have the possibility to build gqrx app bundles for Mac OS X at the moment. Note that gqrx is also available through MacPorts and Homebrew.

**Comment by kenokenobingo** [comment]
I can confirm that installing gqrx with Homebrew works.

**Comment by ra1nb0w** [comment]
works fine with macports (we are also moving to GNURadio 3.8); you have also gqrx-devel that tracks the latest commit.

**Comment by argilo** [comment]
As far as I know, it's possible to build Gqrx on macOS 10.15, since it's working in CI builds.

Binary releases would be nice, so I opened #889 to track that as a feature request.
