### ISSUE TITLE
can not run gqrx. gnuradio3.8 run on my computer, but gqrx said can not find so.3.7.11

### ISSUE THREAD

**Issue by jin-github1002** [csete/gqrx#730]
hello, i installed gqrx from source. when i make it. There are errors about gnuradio3.7. but gnuradio3.8 runs on my computer. why is it? how to deal with it?

dell@dell-XPS-15-9550:~/gqrx.git/build$ cmake ..
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for module 'gnuradio-osmosdr'
--   Found gnuradio-osmosdr, version 0.1.4
-- Found GNURADIO_OSMOSDR: /usr/lib/x86_64-linux-gnu/libgnuradio-osmosdr.so  
-- Found LOG4CPP: /usr/lib/x86_64-linux-gnu/liblog4cpp.so
-- Checking for module 'gmp'
--   No package 'gmp' found
-- Found GMP: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Checking for module 'mpir >= 3.0'
--   No package 'mpir' found
-- Could NOT find MPIR (missing: MPIRXX_LIBRARY MPIR_LIBRARY MPIR_INCLUDE_DIR) 
-- Found MPLIB: /usr/lib/x86_64-linux-gnu/libgmpxx.so  
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   date_time
--   program_options
--   filesystem
--   system
--   regex
--   thread
--   unit_test_framework
--   chrono
--   atomic
-- Found VOLK: Volk::volk  
-- User set python executable /usr/bin/python3
-- Found PythonInterp: /usr/bin/python3 (found version "3.6.9") 
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython3.6m.so (found suitable exact version "3.6.9") 
-- Checking for module 'fftw3f >= 3.0'
--   Found fftw3f , version 3.3.7
-- Found FFTW3f: /usr/lib/x86_64-linux-gnu/libfftw3f.so  
-- Checking for module 'alsa'
--   Found alsa, version 1.1.3
-- Found ALSA 1.1.3
-- Checking for module 'jack'
--   Found jack, version 0.125.0rc1
-- Found jack: /usr/lib/x86_64-linux-gnu/libjack.so
-- Checking for module 'portaudio-2.0'
--   Found portaudio-2.0, version 19
-- Performing Test PORTAUDIO2_FOUND
-- Performing Test PORTAUDIO2_FOUND - Success
-- Found PORTAUDIO: /usr/include  
-- Configuring done
-- Generating done
-- Build files have been written to: /home/dell/gqrx.git/build
dell@dell-XPS-15-9550:~/gqrx.git/build$ make -j3
Scanning dependencies of target gqrx_autogen
[  1%] Automatic MOC for target gqrx
[  1%] Built target gqrx_autogen
[  4%] Generating qrc_textfiles.cpp
[  4%] Generating ui_remote_control_settings.h
[  5%] Generating ui_mainwindow.h
[  6%] Generating ui_afsk1200win.h
[  8%] Generating ui_agc_options.h
[  9%] Generating ui_audio_options.h
[ 10%] Generating ui_demod_options.h
[ 12%] Generating ui_dockaudio.h
[ 13%] Generating ui_dockbookmarks.h
[ 14%] Generating ui_dockfft.h
[ 16%] Generating ui_dockinputctl.h
[ 17%] Generating ui_dockrds.h
[ 20%] Generating ui_dockrxopt.h
[ 20%] Generating ui_ioconfig.h
[ 21%] Generating ui_iq_tool.h
[ 22%] Generating ui_nb_options.h
[ 24%] Generating qrc_icons.cpp
Scanning dependencies of target gqrx
[ 25%] Building CXX object src/CMakeFiles/gqrx.dir/applications/gqrx/receiver.cpp.o
[ 26%] Building CXX object src/CMakeFiles/gqrx.dir/applications/gqrx/main.cpp.o
[ 28%] Building CXX object src/CMakeFiles/gqrx.dir/applications/gqrx/mainwindow.cpp.o
[ 29%] Building CXX object src/CMakeFiles/gqrx.dir/applications/gqrx/remote_control_settings.cpp.o
[ 30%] Building CXX object src/CMakeFiles/gqrx.dir/applications/gqrx/remote_control.cpp.o
[ 32%] Building CXX object src/CMakeFiles/gqrx.dir/applications/gqrx/file_resources.cpp.o
[ 33%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/afsk1200/cafsk12.cpp.o
[ 34%] Building C object src/CMakeFiles/gqrx.dir/dsp/afsk1200/costabf.c.o
[ 36%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/filter/fir_decim.cpp.o
[ 37%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rds/decoder_impl.cc.o
[ 38%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rds/parser_impl.cc.o
[ 40%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/agc_impl.cpp.o
[ 41%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/correct_iq_cc.cpp.o
[ 42%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/lpf.cpp.o
/home/dell/gqrx.git/src/dsp/rds/parser_impl.cc: In member function ‘void gr::rds::parser_impl::decode_optional_content(int, long unsigned int*)’:
/home/dell/gqrx.git/src/dsp/rds/parser_impl.cc:449:36: warning: ‘<<’ in boolean context, did you mean ‘<’ ? [-Wint-in-bool-context]
    label = (free_format[i] && (0xf << ff_pointer));
                               ~~~~~^~~~~~~~~~~~~~
/home/dell/gqrx.git/src/dsp/rds/parser_impl.cc:452:66: warning: ‘<<’ in boolean context, did you mean ‘<’ ? [-Wint-in-bool-context]
    content = (free_format[i] && (int(pow(2, content_length) - 1) << ff_pointer));
                                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
[ 44%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/resampler_xx.cpp.o
[ 45%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rx_agc_xx.cpp.o
[ 46%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rx_demod_am.cpp.o
[ 48%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rx_demod_fm.cpp.o
[ 49%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rx_fft.cpp.o
[ 50%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rx_filter.cpp.o
[ 52%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rx_meter.cpp.o
[ 53%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rx_noise_blanker_cc.cpp.o
[ 54%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/rx_rds.cpp.o
[ 56%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/sniffer_f.cpp.o
[ 57%] Building CXX object src/CMakeFiles/gqrx.dir/dsp/stereo_demod.cpp.o
[ 58%] Building CXX object src/CMakeFiles/gqrx.dir/interfaces/udp_sink_f.cpp.o
[ 60%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/afsk1200win.cpp.o
[ 61%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/agc_options.cpp.o
[ 62%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/audio_options.cpp.o
[ 64%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/bookmarks.cpp.o
[ 65%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/bookmarkstablemodel.cpp.o
[ 66%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/bookmarkstaglist.cpp.o
[ 68%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/ctk/ctkRangeSlider.cpp.o
[ 69%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/demod_options.cpp.o
[ 70%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/dockaudio.cpp.o
[ 72%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/dockbookmarks.cpp.o
[ 73%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/dockfft.cpp.o
[ 74%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/dockinputctl.cpp.o
[ 76%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/dockrds.cpp.o
[ 77%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/dockrxopt.cpp.o
[ 78%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/freqctrl.cpp.o
[ 80%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/ioconfig.cpp.o
[ 81%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/iq_tool.cpp.o
[ 82%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/meter.cpp.o
[ 84%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/nb_options.cpp.o
[ 85%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/plotter.cpp.o
[ 86%] Building CXX object src/CMakeFiles/gqrx.dir/qtgui/qtcolorpicker.cpp.o
[ 88%] Building CXX object src/CMakeFiles/gqrx.dir/receivers/nbrx.cpp.o
[ 89%] Building CXX object src/CMakeFiles/gqrx.dir/receivers/receiver_base.cpp.o
[ 90%] Building CXX object src/CMakeFiles/gqrx.dir/receivers/wfmrx.cpp.o
[ 92%] Building CXX object src/CMakeFiles/gqrx.dir/pulseaudio/pa_device_list.cc.o
[ 93%] Building CXX object src/CMakeFiles/gqrx.dir/pulseaudio/pa_sink.cc.o
[ 94%] Building CXX object src/CMakeFiles/gqrx.dir/pulseaudio/pa_source.cc.o
[ 96%] Building CXX object src/CMakeFiles/gqrx.dir/qrc_icons.cpp.o
[ 97%] Building CXX object src/CMakeFiles/gqrx.dir/qrc_textfiles.cpp.o
[ 98%] Building CXX object src/CMakeFiles/gqrx.dir/gqrx_autogen/mocs_compilation.cpp.o
[100%] Linking CXX executable gqrx
/usr/bin/ld: warning: libgnuradio-runtime.so.3.7.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgnuradio-pmt.so.3.7.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgnuradio-blocks.so.3.7.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgnuradio-iqbalance.so.3.7.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgnuradio-fcd.so.3.7.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgnuradio-fcdproplus.so.3.7.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libgnuradio-uhd.so.3.7.11, needed by /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so, not found (try using -rpath or -rpath-link)
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `pmt::dict_has_key(boost::intrusive_ptr<pmt::pmt_base> const&, boost::intrusive_ptr<pmt::pmt_base> const&)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `gr::msg_accepter::post(boost::intrusive_ptr<pmt::pmt_base>, boost::intrusive_ptr<pmt::pmt_base>)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `pmt::intrusive_ptr_add_ref(pmt::pmt_base*)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `gr::iqbalance::fix_cc::make(float, float)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `gr::blocks::file_source::make(unsigned long, char const*, bool)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `pmt::eqv(boost::intrusive_ptr<pmt::pmt_base> const&, boost::intrusive_ptr<pmt::pmt_base> const&)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `gr::fcd::source_c::make(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `pmt::symbol_to_string[abi:cxx11](boost::intrusive_ptr<pmt::pmt_base> const&)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `pmt::intrusive_ptr_release(pmt::pmt_base*)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `gr::fcdproplus::fcdproplus::make(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, int)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `pmt::list_has(boost::intrusive_ptr<pmt::pmt_base>, boost::intrusive_ptr<pmt::pmt_base> const&)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `gr::iqbalance::optimize_c::make(int)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `gr::uhd::usrp_sink::make(uhd::device_addr_t const&, uhd::stream_args_t const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/libgnuradio-osmosdr.so: undefined reference to `gr::uhd::usrp_source::make(uhd::device_addr_t const&, uhd::stream_args_t const&, bool)'
collect2: error: ld returned 1 exit status
src/CMakeFiles/gqrx.dir/build.make:1659: recipe for target 'src/gqrx' failed
make[2]: *** [src/gqrx] Error 1
CMakeFiles/Makefile2:135: recipe for target 'src/CMakeFiles/gqrx.dir/all' failed
make[1]: *** [src/CMakeFiles/gqrx.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by alexf91** [comment]
Your version of gnuradio-osmosdr is not built for GNU Radio 3.8

**Comment by jin-github1002** [comment]
now i run gqrx.  there is no soapy in the device colomn. what to do?

**Comment by csete** [comment]
I suggest you try a support forum, see for instance https://groups.google.com/forum/#!forum/gqrx
We use github issues for development only and not for user support.
