### ISSUE TITLE
Division by 0 FFT Rate

### ISSUE THREAD

**Issue by al-sharp** [csete/gqrx#738]
Setting FFT FPS rate to 0 (zero) may result in a SIGFPE.
Observed on x86_64 Ubuntu 18.04.

According to A. Csete on Forum:  This is due to a recent update:
https://github.com/csete/gqrx/commit/12a742e51a1553226f8411389f6640c2445148a4
(division by 0 FFT rate)

**Comment by argilo** [comment]
Thanks for reporting! I'll get that fixed.
