### ISSUE TITLE
gqrx and limesdr, can not open GUI. gqrx exited with an exception: soapy_source_c::set_iq_balance_mode() not supported 

### ISSUE THREAD

**Issue by jin-github1002** [csete/gqrx#742]
![Screenshot from 2020-02-04 17-29-23](https://user-images.githubusercontent.com/56423419/73793267-0bebc280-4774-11ea-9623-e77dfe9e5c60.png)

i have run gqrx and limesdr few days ago. But when running them again, there is always the eroor:gqrx exited with an exception:
soapy_source_c::set_iq_balance_mode() not supported
More information can be found by launching it from the console.

Does anyone know the reasons?

thanks  a lot!

**Comment by ra1nb0w** [comment]
change `iq_balance` to `false` on `~/.config/gqrx/default.conf`
