### ISSUE TITLE
[Feature Request] Modulation recognition using machine learning 

### ISSUE THREAD

**Issue by vadimostanin** [csete/gqrx#769]
I think It would be useful feature if modulation "FM" or "AM" will be detected and showed near signal at spectrometer, and further some common modulation (*PSK, FSK, PAM, QAM) also could appears.

**Comment by kolbma** [comment]
Makes this sense for AM vs. FM?
I would see a use-case for information modulation and digi modes.
But to get this working you need a pre-trained model or enough classified samples (count and time) to train a model yourself.
Do you have detailed info to this terrain?

**Comment by argilo** [comment]
It's an interesting idea, but I'm going to close this off because I have no plans to implement it.
