### ISSUE TITLE
Occasional hang with RTL SDR ("Waterfall spaghetti")

### ISSUE THREAD

**Issue by dvdesolve** [csete/gqrx#794]
I own RTL SDR v3 dongle and sometimes I'm facing this weird situation:

![gqrx_hang](https://user-images.githubusercontent.com/32072485/81014838-44c83000-8e66-11ea-85f7-ea06ed3a256d.png)

Waterfall display turns into spaghetti mode, FFT freezes and no reception is possible. The only way to deal with it is to quit from GQRX and run it again (sometimes it's required to do several times).

I use latest stable GQRX and Linux kernel (Arch Linux 64 bit) and observe this problem since the end of 2018 (my first tests with RTL SDR). I've tried with two different dongles: the current v3 and famous "blue Chinese RTLSDR" - the result is the same. Sometimes it starts just after pressing "Play" button and sometimes it hangs after minutes of working.

**Comment by csete** [comment]
I think this happens if the device stops sending samples. If you start gqrx from a terminal there might be some messages about it. Since you experience it with two different dongles, it could be the computers USB port or the USB driver.

**Comment by LongnoseRob** [comment]
Try conencting the USB-dongles to a USB-hub with external power supply.

**Comment by dvdesolve** [comment]
Ok, thank you for the suggestions. I'll try some and if it will be possible to catch  a bug I'll post the results.

As for now I think it could be closed.
