### ISSUE TITLE
Linking to gnuradio 3.8.1 gives undefined reference to `gr::digital::map_bb_impl::s_map_size'

### ISSUE THREAD

**Issue by skinkie** [csete/gqrx#817]
I am running Gentoo and have compiled gnuradio 3.8.1 with the boost qualify placeholders with their full namespace patch. I end up with gqrx as. Does anyone have a tip what could be the cause for this?
```
/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libgnuradio-digital.so.3.8.1.0: undefined reference to `gr::digital::map_bb_impl::s_map_size'
collect2: error: ld returned 1 exit status
```

**Comment by skinkie** [comment]
Was able to solve it: https://github.com/gnuradio/gnuradio/issues/3670

**Comment by argilo** [comment]
I'll close this, since the bug was apparently in GNU Radio and was already fixed.
