### ISSUE TITLE
Gqrx final command

### ISSUE THREAD

**Issue by abroska** [csete/gqrx#822]
./gqrx: error while loading shared libraries: libboost_program_options.so.1.62.0: cannot open shared object file: No such file or directory

**Comment by J-Luc16** [comment]
Same here.

**Comment by alexf91** [comment]
How did you install Gqrx and which distribution do you use?

**Comment by J-Luc16** [comment]
Downloaded from [here (2.11.5)](https://gqrx.dk/download/gqrx-sdr-for-the-raspberry-pi) Raspbian 10.
Gnuradio taken on Raspbian repositories. (apt-get).

J-Luc

**Comment by argilo** [comment]
That blog post is outdated. I would suggest installing Gqrx from Raspbian's package repository with `sudo apt install gqrx-sdr`.

**Comment by J-Luc16** [comment]
It works ! Thanks a lot.
