### ISSUE TITLE
GQRX 

### ISSUE THREAD

**Issue by prohibitory** [csete/gqrx#824]
after running the last command "sudo apt-get install gqrx-sdr" 

my terminal is displaying the following message.

E: Unable to locate package gqrx-sdr

https://launchpad.net/~gqrx/+archive/ubuntu/gqrx-sdr/

**Comment by argilo** [comment]
The Gqrx PPA is no longer maintained. I would suggest installing your distribution's packaged version of Gqrx or building from source instead.
