### ISSUE TITLE
Resizing the GQRX window

### ISSUE THREAD

**Issue by R4UAB** [csete/gqrx#833]
![GQRX](https://user-images.githubusercontent.com/73018237/96333834-e6d68000-1074-11eb-8b23-50d5597c9c99.png)
There is a problem with the extension of the program window. It just isn't available. No full screen button.
OS: Ubuntu 18.04; GnuRadio 3.8.2.0; Python 3.6.9; GQRX: 2.13; Qt version 5.9.5;

**Comment by argilo** [comment]
Thanks for the bug report! I've opened #834 to fix this. Could you let me know if that solves the problem you're seeing?

**Comment by argilo** [comment]
I'm re-opening this, since Gqrx still doesn't work well when the screen height is 768 pixels.
