### ISSUE TITLE
When Demod Off the filter is still shown after restart

### ISSUE THREAD

**Issue by rolnas** [csete/gqrx#854]
When switching to "Demod Off" mode the filter in waterfall is empty initially, but after restart or other changes it shows the last saved filter in waterfall. As a workaround if I remove filter_low_cut and filter_high_cut values in config before starting gqrx it works OK, until I choose again something else as mode and switch back to "Demod Off".

I suggest to introduce filter width as None, to indicate empty filter for the case "Demod Off" of mode or some other solution for this case (possible some more if's in the code).

**Comment by argilo** [comment]
I opened #858 to fix this. If you have a chance to test it, I would appreciate it.

**Comment by rolnas** [comment]
I did testing with v2.13.5 and it works OK now.
Thanks
