### ISSUE TITLE
Dragging X frequency axis breaks waterfall untill left-click on it 

### ISSUE THREAD

**Issue by ankostis** [csete/gqrx#878]
With latest `gqrx-2.13.5-1` build in debian-SID i get a buggy behavior in the waterfal pane: 

When draggingthe frequency to the left, the new part of the waterfall dissappear (becomes black), and a right-click isneeded to begin to be updated: 
![image](https://user-images.githubusercontent.com/501585/99722832-f0ab3300-2ab9-11eb-997a-b832dfdd9888.png)

- Has anybody else pobserved that?
- Is this expected?

**Comment by argilo** [comment]
I checked and the behaviour is the same in 2.12.1 so it's not a new issue. I agree the behaviour is unintuitive. The frequency bar should probably either prevent you from scrolling past the edge of the FFT, or else adjust the hardware frequency to let you see more.

**Comment by ankostis** [comment]
Right-clicking resets X-axis to the previous limits (so frequency had not changed), but clinking sets the offset to the pointed frequency, so there is a code-path that changes the HW-frequency.

**Comment by argilo** [comment]
While looking into this, I noticed that dragging the frequency axis with the center mouse button is meant to change the hardware frequency. Unfortunately that feature was broken, but I've fixed it in #883.

Now that that's fixed, I'll experiment with having the left button adjust the hardware frequency when the edge of the FFT is reached.

**Comment by argilo** [comment]
There's already an issue for this (#330) so I'll close this.
