### ISSUE TITLE
Doesn't start/stop DSP via remote control, but it can start and stop audio recorder.

### ISSUE THREAD

**Issue by jharwinbarrozo** [csete/gqrx#882]
AOS/LOS signalling is coming from gpredict. AOS and LOS signalling were both activated from gpredict radio interface panel.
To repo:
1. Start gpredict and gqrx.
2. Start track button and engage the radio from gpredict, and make sure the frequency is being updated/reflected in gqrx from gpredict (This is to make sure remote control gpredict<-->gpredtct is working)
3. Wait for satellite to pass by or manually controlling the "time controller" feature of gpredict.
4. Don't start dsp of gqrx yet, test will be to wait for the AOS.
5. AOS of satellite has started, DSP never got started in gqrx.

**But** if we start the DSP in gqrx manually, and wait for the AOS to start - I could confirm that it triggers the audio recorder, thus auto audio recording did really work.

Not sure really if this is an issue, or I didn't understand quite well this new feature. I am expecting aos/los signalling from gpredict can START and STOP the GQRX's DSP as well.

**Comment by argilo** [comment]
Gqrx now has a command to start & stop the DSP via remote control, but as far as I know Gpredict does not use it. Since this isn't an issue with Gqrx, I'll close off this report.
