### ISSUE TITLE
Tooltip of Rec button in IQ tool incorrectly says "Button disabled"

### ISSUE THREAD

**Issue by shuyuan-liu** [csete/gqrx#884]
The [🔴 Rec] button in the IQ recording and replay tool has an incorrect tooltip. It says "Button disabled. Please use the record button in the main window." However the button is not disabled and it functions normally.

![image](https://user-images.githubusercontent.com/41851763/99915258-90570400-2cfa-11eb-8f5f-001e3f232874.png)

As far as I can see there's no record button in the main window, except the record button in the Audio tab.

**Comment by argilo** [comment]
Thanks for the bug report. I fixed that in 112791d53f6141e610852c9793c987d7e58870d7, which will go into the next release of gqrx.
