### ISSUE TITLE
gqrx crashes

### ISSUE THREAD

**Issue by ulrichloose** [csete/gqrx#899]
with the following Message:

gqrx exited with an exception:
port number 1 exceeds max of 0
More information can be found by launching it from the console.

if I use RAW I/Q as demodulator.

From console there is no further information shown...

I use a mac with an RTL-SDR Stick and iShowU audio capture driver. I´m not shure, but I think this behavior is new... 

Something completely different (;-)

A small suggestion for improvement ...

In the AudioSpectrum, the set CW offset should be taken into account for CW-L and CW-U. The standard is probably 700 Hz and this is also taken into account in the AudioSpectrum - display is 0 to 1.4 KHz so that 700 Hz is the center. But if you set e.g. 1000 Hz as the CW offset - which is standard with the broadband weather fax at least with fldigi, then it remains at 700 Hz center and the 1000 Hz are not displayed as the center.

https://github.com/csete/gqrx/blob/2cdb903cec6883e9892c83239ada4bac6bb8fad0/src/applications/gqrx/mainwindow.cpp#L1164-L1180

At line 1169 and 1178 the bandwidth ist hardcoded to 1500 Hz. This could be changed with

`1169 uiDockAudio->setFftRange(0,abs(cwofs+cwofs));`
`1178 uiDockAudio->setFftRange(0,cwofs+cwofs);`

**Comment by argilo** [comment]
I'm unable to reproduce the crash. Can you let me know exactly which steps you followed? Which input device are you using? Which buttons did you press after starting Gqrx?

**Comment by argilo** [comment]
> A small suggestion for improvement ...

Please open a separate issue for this. Otherwise it is very difficult to track what work remains to be done.

**Comment by ulrichloose** [comment]
I have to apologize for the second time ...

Apparently the last update bites with one of my own extensions that I save from update to update using Git Stash ... Mea Culpa.
