### ISSUE TITLE
DC remove button doesn't work when "Demod Off" mode is selected

### ISSUE THREAD

**Issue by drmpeg** [csete/gqrx#914]
Toggling the ```DC remove``` button/box has no effect. I've bisected this down to commit https://github.com/csete/gqrx/commit/93bcfae3bf3eb59e49dacfdc036647e447e20fbe

I'll guess the other buttons need to be tested also.

**Comment by argilo** [comment]
The DC remove checkbox is working fine for me and 93bcfae3bf3eb59e49dacfdc036647e447e20fbe appears unrelated.

Can you provide more details about your setup? What operating system are you running on? What input device are you using? Which versions of the dependencies are you using?

**Comment by drmpeg** [comment]
Pretty ancient stuff. Ubuntu 16.04, GNU Radio 3.7.14. I'm using a bladeRF that has a huge DC spike.

I also don't have gr-iqbal if that makes a difference.

**Comment by drmpeg** [comment]
If I comment out the lines:

    if (demod == d_demod)
        return ret;

in receiver.cpp, it works.

**Comment by drmpeg** [comment]
I put a printf() in ```receiver::set_demod()```, and it gets called every time I toggle the checkbox. This is while the DSP is running.

**Comment by argilo** [comment]
Aha, here's the problem:

https://github.com/csete/gqrx/blob/e1fa944518bd1dc945bc4e2e870aeceb7cb1a32c/src/applications/gqrx/receiver.cpp#L478-L482

**Comment by argilo** [comment]
The `d_demod = RX_DEMOD_OFF;` is meant to force `set_demod` to reconfigure the receiver, but that won't happen if the receive mode is already set to "Demod Off".

**Comment by drmpeg** [comment]
Yes, I'm in "Demod Off" mode.

**Comment by argilo** [comment]
OK. That code is an ugly hack. I'll think about how to do this the right way.

**Comment by drmpeg** [comment]
Cool.

**Comment by argilo** [comment]
Fixed in 3cc96629a1b7a2a8d88c459ba006710f297395da.

At first I tried adding a `set_enabled` method to `dc_corr_cc` class to allow it to be switched on and off, but hierarchical blocks don't allow the source pad to be connected directly to the sink pad. :frowning_face:
