### ISSUE TITLE
The audio recording function does not work anymore after trying to play deleted file

### ISSUE THREAD

**Issue by AsciiWolf** [csete/gqrx#96]
For example, I try to record something, then play it. I find out that the recording is bad so I decide to delete it.
After deleting it, I want to make a new recording, but instead of pressing the record button, I accidentally press the play button.
After pressing this button, an error message is shown in a status bar but the file appears to be still playing and the playback could not be stopped...
At this point, Gqrx must be restarted to make the sound recording function work again...

![gqrx_playback_error](https://f.cloud.github.com/assets/2339930/896681/07b8dfc4-fae4-11e2-9bf4-c564d12d6216.png)

**Comment by AsciiWolf** [comment]
Any news regarding this old issue? It seems to be still present in Gqrx 2.6.

**Comment by csete** [comment]
Sorry, but the fact that an issue is old is not going to get it fixed. Since I get very little effective help with the project and I also have other projects to work on in my spare time, issues are going to be prioritized.

**Comment by csete** [comment]
@AsciiWolf  this should be fixed now, thanks to @alexf91
