### ISSUE TITLE
Spectrum is mirrored when filter or demodulator changes (rtl_tcp)

### ISSUE THREAD

**Issue by piranha32** [csete/gqrx#99]
DC correction appears to toggle every time a filter or demodulator are selected from combo boxes. This behavior can be seen on the screen capture from running gqrx: http://youtu.be/Mk9xnJucil8
Mirror images appear and disappear every time a filter or demodulator setting is selected. It can be also observed when there is no change in settings: in the video the filter is set to "Wide" and I'm clicking "Wide" to close the combo box. The same happens for demod selection: the change is from "Wide FM (stereo)" to "Wide FM (stereo)". The toggling does not affect the state of the "DC cancel" checkbox.
receiver::connect_all() is not called when the toggling happens.
gqrx is compiled from code cloned from github master. Latest commit:

```
commit 1ee3d787bc5564b6fac8f06d3c0dbd09b3d5e8cf
Author: Alexandru Csete <oz9aec@gmail.com>
Date:   Sun Aug 4 10:00:03 2013 +0200

    Also catch boost::program_options::unknown_option exception.
```

**Comment by kukabu** [comment]
http://lists.osmocom.org/pipermail/osmocom-sdr/2016-August/001480.html

Has anyone tested this?

**Comment by csete** [comment]
Thanks for the tip @kukabu 
I haven't seen that before but I am going to give it a try. We already have some patches in the [csete/gr-osmosdr-gqrx](https://github.com/csete/gr-osmosdr-gqrx) repository.

**Comment by andreer** [comment]
I tried applying these patches and recompiling gr-osmosdr and they definitely removed the problem for me. Before, I experienced bizarre effects such as frequencies shifting when I enabled/disabled the RDS function for WFM.

**Comment by csete** [comment]
Thanks for the info @andreer 

I will include the patches in our Ubuntu packages the next time I am packaging.

**Comment by kukabu** [comment]
Good news! The patches in gr-osmosdr now.

**Comment by andreer** [comment]
Good news indeed! Hopefully this problem will be gone for everyone now.

**Comment by csete** [comment]
Indeed, I sent a mail to Dimitri back in April asking about these patches, and now they are applied. So, I will update our PPA in the next round of packaging, then we can close this issue :-)

**Comment by csete** [comment]
Updated gr-osmosdr is now available in the myriadrf PPA.
